const leetcodeProblems = [
  "Two Sum",
  "Add Two Numbers",
  "Longest Substring Without Repeating Characters",
  "Median of Two Sorted Arrays",
  "Longest Palindromic Substring",
  "Zigzag Conversion",
  "Reverse Integer",
  "String to Integer (atoi)",
  "Palindrome Number",
  "Regular Expression Matching",
  "Container With Most Water",
  "Integer to Roman",
  "Roman to Integer",
  "Longest Common Prefix",
  "3Sum",
  "3Sum Closest",
  "Letter Combinations of a Phone Number",
  "4Sum",
  "Remove Nth Node From End of List",
  "Valid Parentheses",
  "Merge Two Sorted Lists",
  "Generate Parentheses",
  "Merge k Sorted Lists",
  "Swap Nodes in Pairs",
  "Reverse Nodes in k-Group",
  "Remove Duplicates from Sorted Array",
  "Remove Element",
  "Find the Index of the First Occurrence in a String",
  "Divide Two Integers",
  "Substring with Concatenation of All Words",
  "Next Permutation",
  "Longest Valid Parentheses",
  "Search in Rotated Sorted Array",
  "Find First and Last Position of Element in Sorted Array",
  "Search Insert Position",
  "Valid Sudoku",
  "Sudoku Solver",
  "Count and Say",
  "Combination Sum",
  "Combination Sum II",
  "First Missing Positive",
  "Trapping Rain Water",
  "Multiply Strings",
  "Wildcard Matching",
  "Jump Game II",
  "Permutations",
  "Permutations II",
  "Rotate Image",
  "Group Anagrams",
  "Pow(x, n)",
  "N-Queens",
  "N-Queens II",
  "Maximum Subarray",
  "Spiral Matrix",
  "Jump Game",
  "Merge Intervals",
  "Insert Interval",
  "Length of Last Word",
  "Spiral Matrix II",
  "Permutation Sequence",
  "Rotate List",
  "Unique Paths",
  "Unique Paths II",
  "Minimum Path Sum",
  "Valid Number",
  "Plus One",
  "Add Binary",
  "Text Justification",
  "Sqrt(x)",
  "Climbing Stairs",
  "Simplify Path",
  "Edit Distance",
  "Set Matrix Zeroes",
  "Search a 2D Matrix",
  "Sort Colors",
  "Minimum Window Substring",
  "Combinations",
  "Subsets",
  "Word Search",
  "Remove Duplicates from Sorted Array II",
  "Search in Rotated Sorted Array II",
  "Remove Duplicates from Sorted List II",
  "Remove Duplicates from Sorted List",
  "Largest Rectangle in Histogram",
  "Maximal Rectangle",
  "Partition List",
  "Scramble String",
  "Merge Sorted Array",
  "Gray Code",
  "Subsets II",
  "Decode Ways",
  "Reverse Linked List II",
  "Restore IP Addresses",
  "Binary Tree Inorder Traversal",
  "Unique Binary Search Trees II",
  "Unique Binary Search Trees",
  "Interleaving String",
  "Validate Binary Search Tree",
  "Recover Binary Search Tree",
  "Same Tree",
  "Symmetric Tree",
  "Binary Tree Level Order Traversal",
  "Binary Tree Zigzag Level Order Traversal",
  "Maximum Depth of Binary Tree",
  "Construct Binary Tree from Preorder and Inorder Traversal",
  "Construct Binary Tree from Inorder and Postorder Traversal",
  "Binary Tree Level Order Traversal II",
  "Convert Sorted Array to Binary Search Tree",
  "Convert Sorted List to Binary Search Tree",
  "Balanced Binary Tree",
  "Minimum Depth of Binary Tree",
  "Path Sum",
  "Path Sum II",
  "Flatten Binary Tree to Linked List",
  "Distinct Subsequences",
  "Populating Next Right Pointers in Each Node",
  "Populating Next Right Pointers in Each Node II",
  "Pascal's Triangle",
  "Pascal's Triangle II",
  "Triangle",
  "Best Time to Buy and Sell Stock",
  "Best Time to Buy and Sell Stock II",
  "Best Time to Buy and Sell Stock III",
  "Binary Tree Maximum Path Sum",
  "Valid Palindrome",
  "Word Ladder II",
  "Word Ladder",
  "Longest Consecutive Sequence",
  "Sum Root to Leaf Numbers",
  "Surrounded Regions",
  "Palindrome Partitioning",
  "Palindrome Partitioning II",
  "Clone Graph",
  "Gas Station",
  "Candy",
  "Single Number",
  "Single Number II",
  "Copy List with Random Pointer",
  "Word Break",
  "Word Break II",
  "Linked List Cycle",
  "Linked List Cycle II",
  "Reorder List",
  "Binary Tree Preorder Traversal",
  "Binary Tree Postorder Traversal",
  "LRU Cache",
  "Insertion Sort List",
  "Sort List",
  "Max Points on a Line",
  "Evaluate Reverse Polish Notation",
  "Reverse Words in a String",
  "Maximum Product Subarray",
  "Find Minimum in Rotated Sorted Array",
  "Find Minimum in Rotated Sorted Array II",
  "Min Stack",
  "Binary Tree Upside Down",
  "Read N Characters Given Read4",
  "Read N Characters Given read4 II - Call Multiple Times",
  "Longest Substring with At Most Two Distinct Characters",
  "Intersection of Two Linked Lists",
  "One Edit Distance",
  "Find Peak Element",
  "Missing Ranges",
  "Maximum Gap",
  "Compare Version Numbers",
  "Fraction to Recurring Decimal",
  "Two Sum II - Input Array Is Sorted",
  "Excel Sheet Column Title",
  "Majority Element",
  "Two Sum III - Data structure design",
  "Excel Sheet Column Number",
  "Factorial Trailing Zeroes",
  "Binary Search Tree Iterator",
  "Dungeon Game",
  "Combine Two Tables",
  "Second Highest Salary",
  "Nth Highest Salary",
  "Rank Scores",
  "Largest Number",
  "Consecutive Numbers",
  "Employees Earning More Than Their Managers",
  "Duplicate Emails",
  "Customers Who Never Order",
  "Department Highest Salary",
  "Department Top Three Salaries",
  "Reverse Words in a String II",
  "Repeated DNA Sequences",
  "Best Time to Buy and Sell Stock IV",
  "Rotate Array",
  "Reverse Bits",
  "Number of 1 Bits",
  "Word Frequency",
  "Valid Phone Numbers",
  "Transpose File",
  "Tenth Line",
  "Delete Duplicate Emails",
  "Rising Temperature",
  "House Robber",
  "Binary Tree Right Side View",
  "Number of Islands",
  "Bitwise AND of Numbers Range",
  "Happy Number",
  "Remove Linked List Elements",
  "Count Primes",
  "Isomorphic Strings",
  "Reverse Linked List",
  "Course Schedule",
  "Implement Trie (Prefix Tree)",
  "Minimum Size Subarray Sum",
  "Course Schedule II",
  "Design Add and Search Words Data Structure",
  "Word Search II",
  "House Robber II",
  "Shortest Palindrome",
  "Kth Largest Element in an Array",
  "Combination Sum III",
  "Contains Duplicate",
  "The Skyline Problem",
  "Contains Duplicate II",
  "Contains Duplicate III",
  "Maximal Square",
  "Count Complete Tree Nodes",
  "Rectangle Area",
  "Basic Calculator",
  "Implement Stack using Queues",
  "Invert Binary Tree",
  "Basic Calculator II",
  "Summary Ranges",
  "Majority Element II",
  "Kth Smallest Element in a BST",
  "Power of Two",
  "Implement Queue using Stacks",
  "Number of Digit One",
  "Palindrome Linked List",
  "Lowest Common Ancestor of a Binary Search Tree",
  "Lowest Common Ancestor of a Binary Tree",
  "Delete Node in a Linked List",
  "Product of Array Except Self",
  "Sliding Window Maximum",
  "Search a 2D Matrix II",
  "Different Ways to Add Parentheses",
  "Valid Anagram",
  "Shortest Word Distance",
  "Shortest Word Distance II",
  "Shortest Word Distance III",
  "Strobogrammatic Number",
  "Strobogrammatic Number II",
  "Strobogrammatic Number III",
  "Group Shifted Strings",
  "Count Univalue Subtrees",
  "Flatten 2D Vector",
  "Meeting Rooms",
  "Meeting Rooms II",
  "Factor Combinations",
  "Verify Preorder Sequence in Binary Search Tree",
  "Paint House",
  "Binary Tree Paths",
  "Add Digits",
  "3Sum Smaller",
  "Single Number III",
  "Graph Valid Tree",
  "Trips and Users",
  "Ugly Number",
  "Ugly Number II",
  "Paint House II",
  "Palindrome Permutation",
  "Palindrome Permutation II",
  "Missing Number",
  "Alien Dictionary",
  "Closest Binary Search Tree Value",
  "Encode and Decode Strings",
  "Closest Binary Search Tree Value II",
  "Integer to English Words",
  "H-Index",
  "H-Index II",
  "Paint Fence",
  "Find the Celebrity",
  "First Bad Version",
  "Perfect Squares",
  "Wiggle Sort",
  "Zigzag Iterator",
  "Expression Add Operators",
  "Move Zeroes",
  "Peeking Iterator",
  "Inorder Successor in BST",
  "Walls and Gates",
  "Find the Duplicate Number",
  "Unique Word Abbreviation",
  "Game of Life",
  "Word Pattern",
  "Word Pattern II",
  "Nim Game",
  "Flip Game",
  "Flip Game II",
  "Find Median from Data Stream",
  "Best Meeting Point",
  "Serialize and Deserialize Binary Tree",
  "Binary Tree Longest Consecutive Sequence",
  "Bulls and Cows",
  "Longest Increasing Subsequence",
  "Remove Invalid Parentheses",
  "Smallest Rectangle Enclosing Black Pixels",
  "Range Sum Query - Immutable",
  "Range Sum Query 2D - Immutable",
  "Number of Islands II",
  "Additive Number",
  "Range Sum Query - Mutable",
  "Range Sum Query 2D - Mutable",
  "Best Time to Buy and Sell Stock with Cooldown",
  "Minimum Height Trees",
  "Sparse Matrix Multiplication",
  "Burst Balloons",
  "Super Ugly Number",
  "Binary Tree Vertical Order Traversal",
  "Count of Smaller Numbers After Self",
  "Remove Duplicate Letters",
  "Shortest Distance from All Buildings",
  "Maximum Product of Word Lengths",
  "Bulb Switcher",
  "Generalized Abbreviation",
  "Create Maximum Number",
  "Coin Change",
  "Number of Connected Components in an Undirected Graph",
  "Wiggle Sort II",
  "Maximum Size Subarray Sum Equals k",
  "Power of Three",
  "Count of Range Sum",
  "Odd Even Linked List",
  "Longest Increasing Path in a Matrix",
  "Patching Array",
  "Verify Preorder Serialization of a Binary Tree",
  "Reconstruct Itinerary",
  "Largest BST Subtree",
  "Increasing Triplet Subsequence",
  "Self Crossing",
  "Palindrome Pairs",
  "House Robber III",
  "Counting Bits",
  "Nested List Weight Sum",
  "Longest Substring with At Most K Distinct Characters",
  "Flatten Nested List Iterator",
  "Power of Four",
  "Integer Break",
  "Reverse String",
  "Reverse Vowels of a String",
  "Moving Average from Data Stream",
  "Top K Frequent Elements",
  "Design Tic-Tac-Toe",
  "Intersection of Two Arrays",
  "Intersection of Two Arrays II",
  "Android Unlock Patterns",
  "Data Stream as Disjoint Intervals",
  "Design Snake Game",
  "Russian Doll Envelopes",
  "Design Twitter",
  "Line Reflection",
  "Count Numbers with Unique Digits",
  "Rearrange String k Distance Apart",
  "Logger Rate Limiter",
  "Sort Transformed Array",
  "Bomb Enemy",
  "Design Hit Counter",
  "Max Sum of Rectangle No Larger Than K",
  "Nested List Weight Sum II",
  "Water and Jug Problem",
  "Find Leaves of Binary Tree",
  "Valid Perfect Square",
  "Largest Divisible Subset",
  "Plus One Linked List",
  "Range Addition",
  "Sum of Two Integers",
  "Super Pow",
  "Find K Pairs with Smallest Sums",
  "Guess Number Higher or Lower",
  "Guess Number Higher or Lower II",
  "Wiggle Subsequence",
  "Combination Sum IV",
  "Kth Smallest Element in a Sorted Matrix",
  "Design Phone Directory",
  "Insert Delete GetRandom O(1)",
  "Insert Delete GetRandom O(1) - Duplicates allowed",
  "Linked List Random Node",
  "Ransom Note",
  "Shuffle an Array",
  "Mini Parser",
  "Lexicographical Numbers",
  "First Unique Character in a String",
  "Longest Absolute File Path",
  "Find the Difference",
  "Elimination Game",
  "Perfect Rectangle",
  "Is Subsequence",
  "UTF-8 Validation",
  "Decode String",
  "Longest Substring with At Least K Repeating Characters",
  "Rotate Function",
  "Integer Replacement",
  "Random Pick Index",
  "Evaluate Division",
  "Nth Digit",
  "Binary Watch",
  "Remove K Digits",
  "Frog Jump",
  "Sum of Left Leaves",
  "Convert a Number to Hexadecimal",
  "Queue Reconstruction by Height",
  "Trapping Rain Water II",
  "Valid Word Abbreviation",
  "Longest Palindrome",
  "Split Array Largest Sum",
  "Minimum Unique Word Abbreviation",
  "Fizz Buzz",
  "Arithmetic Slices",
  "Third Maximum Number",
  "Add Strings",
  "Partition Equal Subset Sum",
  "Pacific Atlantic Water Flow",
  "Sentence Screen Fitting",
  "Battleships in a Board",
  "Strong Password Checker",
  "Maximum XOR of Two Numbers in an Array",
  "Valid Word Square",
  "Reconstruct Original Digits from English",
  "Longest Repeating Character Replacement",
  "Word Squares",
  "Convert Binary Search Tree to Sorted Doubly Linked List",
  "Construct Quad Tree",
  "Serialize and Deserialize N-ary Tree",
  "N-ary Tree Level Order Traversal",
  "Flatten a Multilevel Doubly Linked List",
  "Encode N-ary Tree to Binary Tree",
  "All Oone Data Structure",
  "Minimum Genetic Mutation",
  "Number of Segments in a String",
  "Non-overlapping Intervals",
  "Find Right Interval",
  "Path Sum III",
  "Find All Anagrams in a String",
  "Find All Anagrams in a String",
  "Ternary Expression Parser",
  "K-th Smallest in Lexicographical Order",
  "Arranging Coins",
  "Find All Duplicates in an Array",
  "String Compression",
  "Sequence Reconstruction",
  "Add Two Numbers II",
  "Arithmetic Slices II - Subsequence",
  "Number of Boomerangs",
  "Find All Numbers Disappeared in an Array",
  "Serialize and Deserialize BST",
  "Delete Node in a BST",
  "Sort Characters By Frequency",
  "Minimum Number of Arrows to Burst Balloons",
  "Minimum Moves to Equal Array Elements",
  "4Sum II",
  "Assign Cookies",
  "132 Pattern",
  "Circular Array Loop",
  "Poor Pigs",
  "Repeated Substring Pattern",
  "LFU Cache",
  "Hamming Distance",
  "Minimum Moves to Equal Array Elements II",
  "Island Perimeter",
  "Can I Win",
  "Optimal Account Balancing",
  "Count The Repetitions",
  "Unique Substrings in Wraparound String",
  "Validate IP Address",
  "Convex Polygon",
  "Implement Rand10() Using Rand7()",
  "Encode String with Shortest Length",
  "Concatenated Words",
  "Matchsticks to Square",
  "Ones and Zeroes",
  "Heaters",
  "Number Complement",
  "Total Hamming Distance",
  "Generate Random Point in a Circle",
  "Largest Palindrome Product",
  "Sliding Window Median",
  "Magical String",
  "License Key Formatting",
  "Smallest Good Base",
  "Find Permutation",
  "Max Consecutive Ones",
  "Predict the Winner",
  "Max Consecutive Ones II",
  "Zuma Game",
  "Robot Room Cleaner",
  "The Maze",
  "Non-decreasing Subsequences",
  "Construct the Rectangle",
  "Reverse Pairs",
  "Target Sum",
  "Teemo Attacking",
  "Next Greater Element I",
  "Random Point in Non-overlapping Rectangles",
  "Diagonal Traverse",
  "The Maze III",
  "Keyboard Row",
  "Find Mode in Binary Search Tree",
  "IPO",
  "Next Greater Element II",
  "Base 7",
  "The Maze II",
  "Relative Ranks",
  "Perfect Number",
  "Most Frequent Subtree Sum",
  "Fibonacci Number",
  "Inorder Successor in BST II",
  "Game Play Analysis I",
  "Game Play Analysis II",
  "Find Bottom Left Tree Value",
  "Freedom Trail",
  "Find Largest Value in Each Tree Row",
  "Longest Palindromic Subsequence",
  "Super Washing Machines",
  "Coin Change II",
  "Random Flip Matrix",
  "Detect Capital",
  "Longest Uncommon Subsequence I",
  "Longest Uncommon Subsequence II",
  "Continuous Subarray Sum",
  "Longest Word in Dictionary through Deleting",
  "Contiguous Array",
  "Beautiful Arrangement",
  "Word Abbreviation",
  "Random Pick with Weight",
  "Minesweeper",
  "Minimum Absolute Difference in BST",
  "Lonely Pixel I",
  "K-diff Pairs in an Array",
  "Lonely Pixel II",
  "Game Play Analysis III",
  "Encode and Decode TinyURL",
  "Construct Binary Tree from String",
  "Complex Number Multiplication",
  "Convert BST to Greater Tree",
  "Minimum Time Difference",
  "Single Element in a Sorted Array",
  "Reverse String II",
  "01 Matrix",
  "Diameter of Binary Tree",
  "Output Contest Matches",
  "Boundary of Binary Tree",
  "Remove Boxes",
  "Number of Provinces",
  "Split Array with Equal Sum",
  "Binary Tree Longest Consecutive Sequence II",
  "Game Play Analysis IV",
  "Student Attendance Record I",
  "Student Attendance Record II",
  "Optimal Division",
  "Brick Wall",
  "Split Concatenated Strings",
  "Next Greater Element III",
  "Reverse Words in a String III",
  "Logical OR of Two Binary Grids Represented as Quad-Trees",
  "Maximum Depth of N-ary Tree",
  "Subarray Sum Equals K",
  "Array Partition",
  "Longest Line of Consecutive One in Matrix",
  "Binary Tree Tilt",
  "Find the Closest Palindrome",
  "Array Nesting",
  "Reshape the Matrix",
  "Permutation in String",
  "Maximum Vacation Days",
  "Median Employee Salary",
  "Managers with at Least 5 Direct Reports",
  "Find Median Given Frequency of Numbers",
  "Subtree of Another Tree",
  "Squirrel Simulation",
  "Winning Candidate",
  "Distribute Candies",
  "Out of Boundary Paths",
  "Employee Bonus",
  "Get Highest Answer Rate Question",
  "Find Cumulative Salary of an Employee",
  "Count Student Number in Departments",
  "Shortest Unsorted Continuous Subarray",
  "Kill Process",
  "Delete Operation for Two Strings",
  "Find Customer Referee",
  "Investments in 2016",
  "Customer Placing the Largest Number of Orders",
  "Erect the Fence",
  "Design In-Memory File System",
  "N-ary Tree Preorder Traversal",
  "N-ary Tree Postorder Traversal",
  "Tag Validator",
  "Fraction Addition and Subtraction",
  "Valid Square",
  "Longest Harmonious Subsequence",
  "Big Countries",
  "Classes More Than 5 Students",
  "Friend Requests I: Overall Acceptance Rate",
  "Range Addition II",
  "Minimum Index Sum of Two Lists",
  "Non-negative Integers without Consecutive Ones",
  "Human Traffic of Stadium",
  "Friend Requests II: Who Has the Most Friends",
  "Consecutive Available Seats",
  "Design Compressed String Iterator",
  "Can Place Flowers",
  "Construct String from Binary Tree",
  "Sales Person",
  "Tree Node",
  "Find Duplicate File in System",
  "Triangle Judgement",
  "Valid Triangle Number",
  "Shortest Distance in a Plane",
  "Shortest Distance in a Line",
  "Second Degree Follower",
  "Average Salary: Departments VS Company",
  "Add Bold Tag in String",
  "Merge Two Binary Trees",
  "Students Report By Geography",
  "Biggest Single Number",
  "Not Boring Movies",
  "Task Scheduler",
  "Design Circular Queue",
  "Add One Row to Tree",
  "Maximum Distance in Arrays",
  "Minimum Factorization",
  "Exchange Seats",
  "Swap Salary",
  "Maximum Product of Three Numbers",
  "K Inverse Pairs Array",
  "Course Schedule III",
  "Design Excel Sum Formula",
  "Smallest Range Covering Elements from K Lists",
  "Sum of Square Numbers",
  "Find the Derangement of An Array",
  "Design Log Storage System",
  "Exclusive Time of Functions",
  "Average of Levels in Binary Tree",
  "Shopping Offers",
  "Decode Ways II",
  "Solve the Equation",
  "Design Circular Deque",
  "Design Search Autocomplete System",
  "Maximum Average Subarray I",
  "Maximum Average Subarray II",
  "Set Mismatch",
  "Maximum Length of Pair Chain",
  "Palindromic Substrings",
  "Replace Words",
  "Dota2 Senate",
  "2 Keys Keyboard",
  "4 Keys Keyboard",
  "Find Duplicate Subtrees",
  "Two Sum IV - Input is a BST",
  "Maximum Binary Tree",
  "Print Binary Tree",
  "Coin Path",
  "Robot Return to Origin",
  "Find K Closest Elements",
  "Split Array into Consecutive Subsequences",
  "Remove 9",
  "Image Smoother",
  "Maximum Width of Binary Tree",
  "Equal Tree Partition",
  "Strange Printer",
  "Non-decreasing Array",
  "Path Sum IV",
  "Beautiful Arrangement II",
  "Kth Smallest Number in Multiplication Table",
  "Trim a Binary Search Tree",
  "Maximum Swap",
  "Second Minimum Node In a Binary Tree",
  "Bulb Switcher II",
  "Number of Longest Increasing Subsequence",
  "Longest Continuous Increasing Subsequence",
  "Cut Off Trees for Golf Event",
  "Implement Magic Dictionary",
  "Map Sum Pairs",
  "Valid Parenthesis String",
  "24 Game",
  "Valid Palindrome II",
  "Next Closest Time",
  "Baseball Game",
  "K Empty Slots",
  "Redundant Connection",
  "Redundant Connection II",
  "Repeated String Match",
  "Longest Univalue Path",
  "Knight Probability in Chessboard",
  "Maximum Sum of 3 Non-Overlapping Subarrays",
  "Employee Importance",
  "Stickers to Spell Word",
  "Top K Frequent Words",
  "Binary Number with Alternating Bits",
  "Number of Distinct Islands",
  "Max Area of Island",
  "Count Binary Substrings",
  "Degree of an Array",
  "Partition to K Equal Sum Subsets",
  "Falling Squares",
  "Search in a Binary Search Tree",
  "Insert into a Binary Search Tree",
  "Search in a Sorted Array of Unknown Size",
  "Kth Largest Element in a Stream",
  "Binary Search",
  "Design HashSet",
  "Design HashMap",
  "Design Linked List",
  "Insert into a Sorted Circular Linked List",
  "To Lower Case",
  "Random Pick with Blacklist",
  "Number of Distinct Islands II",
  "Minimum ASCII Delete Sum for Two Strings",
  "Subarray Product Less Than K",
  "Best Time to Buy and Sell Stock with Transaction Fee",
  "Range Module",
  "Max Stack",
  "1-bit and 2-bit Characters",
  "Maximum Length of Repeated Subarray",
  "Find K-th Smallest Pair Distance",
  "Longest Word in Dictionary",
  "Accounts Merge",
  "Remove Comments",
  "Candy Crush",
  "Find Pivot Index",
  "Split Linked List in Parts",
  "Number of Atoms",
  "Minimum Window Subsequence",
  "Self Dividing Numbers",
  "My Calendar I",
  "Count Different Palindromic Subsequences",
  "My Calendar II",
  "My Calendar III",
  "Flood Fill",
  "Sentence Similarity",
  "Asteroid Collision",
  "Parse Lisp Expression",
  "Sentence Similarity II",
  "Monotone Increasing Digits",
  "Daily Temperatures",
  "Delete and Earn",
  "Cherry Pickup",
  "Closest Leaf in a Binary Tree",
  "Network Delay Time",
  "Find Smallest Letter Greater Than Target",
  "Prefix and Suffix Search",
  "Min Cost Climbing Stairs",
  "Largest Number At Least Twice of Others",
  "Shortest Completing Word",
  "Contain Virus",
  "Number Of Corner Rectangles",
  "Open the Lock",
  "Cracking the Safe",
  "Reach a Number",
  "Pour Water",
  "Pyramid Transition Matrix",
  "Set Intersection Size At Least Two",
  "Bold Words in String",
  "Employee Free Time",
  "Find Anagram Mappings",
  "Special Binary String",
  "Prime Number of Set Bits in Binary Representation",
  "Partition Labels",
  "Largest Plus Sign",
  "Couples Holding Hands",
  "Toeplitz Matrix",
  "Reorganize String",
  "Max Chunks To Make Sorted II",
  "Max Chunks To Make Sorted",
  "Basic Calculator IV",
  "Jewels and Stones",
  "Basic Calculator III",
  "Sliding Puzzle",
  "Minimize Max Distance to Gas Station",
  "Global and Local Inversions",
  "Split BST",
  "Swap Adjacent in LR String",
  "Swim in Rising Water",
  "K-th Symbol in Grammar",
  "Reaching Points",
  "Rabbits in Forest",
  "Transform to Chessboard",
  "Minimum Distance Between BST Nodes",
  "Letter Case Permutation",
  "Is Graph Bipartite?",
  "K-th Smallest Prime Fraction",
  "Cheapest Flights Within K Stops",
  "Rotated Digits",
  "Escape The Ghosts",
  "Domino and Tromino Tiling",
  "Custom Sort String",
  "Number of Matching Subsequences",
  "Preimage Size of Factorial Zeroes Function",
  "Valid Tic-Tac-Toe State",
  "Number of Subarrays with Bounded Maximum",
  "Rotate String",
  "All Paths From Source to Target",
  "Smallest Rotation with Highest Score",
  "Champagne Tower",
  "Similar RGB Color",
  "Minimum Swaps To Make Sequences Increasing",
  "Find Eventual Safe States",
  "Bricks Falling When Hit",
  "Unique Morse Code Words",
  "Split Array With Same Average",
  "Number of Lines To Write String",
  "Max Increase to Keep City Skyline",
  "Soup Servings",
  "Expressive Words",
  "Chalkboard XOR Game",
  "Subdomain Visit Count",
  "Largest Triangle Area",
  "Largest Sum of Averages",
  "Binary Tree Pruning",
  "Bus Routes",
  "Ambiguous Coordinates",
  "Linked List Components",
  "Race Car",
  "Most Common Word",
  "Short Encoding of Words",
  "Shortest Distance to a Character",
  "Card Flipping Game",
  "Binary Trees With Factors",
  "Goat Latin",
  "Friends Of Appropriate Ages",
  "Most Profit Assigning Work",
  "Making A Large Island",
  "Count Unique Characters of All Substrings of a Given String",
  "Consecutive Numbers Sum",
  "Positions of Large Groups",
  "Masking Personal Information",
  "Flipping an Image",
  "Find And Replace in String",
  "Sum of Distances in Tree",
  "Image Overlap",
  "Rectangle Overlap",
  "New 21 Game",
  "Push Dominoes",
  "Similar String Groups",
  "Magic Squares In Grid",
  "Keys and Rooms",
  "Split Array into Fibonacci Sequence",
  "Guess the Word",
  "Backspace String Compare",
  "Longest Mountain in Array",
  "Hand of Straights",
  "Shortest Path Visiting All Nodes",
  "Shifting Letters",
  "Maximize Distance to Closest Person",
  "Rectangle Area II",
  "Loud and Rich",
  "Peak Index in a Mountain Array",
  "Car Fleet",
  "K-Similar Strings",
  "Exam Room",
  "Score of Parentheses",
  "Minimum Cost to Hire K Workers",
  "Mirror Reflection",
  "Buddy Strings",
  "Lemonade Change",
  "Score After Flipping Matrix",
  "Shortest Subarray with Sum at Least K",
  "All Nodes Distance K in Binary Tree",
  "Shortest Path to Get All Keys",
  "Smallest Subtree with all the Deepest Nodes",
  "Prime Palindrome",
  "Transpose Matrix",
  "Binary Gap",
  "Reordered Power of 2",
  "Advantage Shuffle",
  "Minimum Number of Refueling Stops",
  "Leaf-Similar Trees",
  "Length of Longest Fibonacci Subsequence",
  "Walking Robot Simulation",
  "Koko Eating Bananas",
  "Middle of the Linked List",
  "Stone Game",
  "Nth Magical Number",
  "Profitable Schemes",
  "Decoded String at Index",
  "Boats to Save People",
  "Reachable Nodes In Subdivided Graph",
  "Projection Area of 3D Shapes",
  "Uncommon Words from Two Sentences",
  "Spiral Matrix III",
  "Possible Bipartition",
  "Super Egg Drop",
  "Fair Candy Swap",
  "Construct Binary Tree from Preorder and Postorder Traversal",
  "Find and Replace Pattern",
  "Sum of Subsequence Widths",
  "Surface Area of 3D Shapes",
  "Groups of Special-Equivalent Strings",
  "All Possible Full Binary Trees",
  "Maximum Frequency Stack",
  "Monotonic Array",
  "Increasing Order Search Tree",
  "Bitwise ORs of Subarrays",
  "Orderly Queue",
  "RLE Iterator",
  "Online Stock Span",
  "Numbers At Most N Given Digit Set",
  "Valid Permutations for DI Sequence",
  "Fruit Into Baskets",
  "Sort Array By Parity",
  "Super Palindromes",
  "Sum of Subarray Minimums",
  "Smallest Range I",
  "Snakes and Ladders",
  "Smallest Range II",
  "Online Election",
  "Sort an Array",
  "Cat and Mouse",
  "X of a Kind in a Deck of Cards",
  "Partition Array into Disjoint Intervals",
  "Word Subsets",
  "Reverse Only Letters",
  "Maximum Sum Circular Subarray",
  "Complete Binary Tree Inserter",
  "Number of Music Playlists",
  "Minimum Add to Make Parentheses Valid",
  "Sort Array By Parity II",
  "3Sum With Multiplicity",
  "Minimize Malware Spread",
  "Long Pressed Name",
  "Flip String to Monotone Increasing",
  "Three Equal Parts",
  "Minimize Malware Spread II",
  "Unique Email Addresses",
  "Binary Subarrays With Sum",
  "Minimum Falling Path Sum",
  "Beautiful Array",
  "Number of Recent Calls",
  "Shortest Bridge",
  "Knight Dialer",
  "Stamping The Sequence",
  "Reorder Data in Log Files",
  "Range Sum of BST",
  "Minimum Area Rectangle",
  "Distinct Subsequences II",
  "Valid Mountain Array",
  "DI String Match",
  "Find the Shortest Superstring",
  "Delete Columns to Make Sorted",
  "Minimum Increment to Make Array Unique",
  "Validate Stack Sequences",
  "Most Stones Removed with Same Row or Column",
  "Bag of Tokens",
  "Largest Time for Given Digits",
  "Reveal Cards In Increasing Order",
  "Flip Equivalent Binary Trees",
  "Largest Component Size by Common Factor",
  "Verifying an Alien Dictionary",
  "Array of Doubled Pairs",
  "Delete Columns to Make Sorted II",
  "Tallest Billboard",
  "Prison Cells After N Days",
  "Check Completeness of a Binary Tree",
  "Regions Cut By Slashes",
  "Delete Columns to Make Sorted III",
  "N-Repeated Element in Size 2N Array",
  "Maximum Width Ramp",
  "Minimum Area Rectangle II",
  "Least Operators to Express Number",
  "Univalued Binary Tree",
  "Vowel Spellchecker",
  "Numbers With Same Consecutive Differences",
  "Binary Tree Cameras",
  "Pancake Sorting",
  "Powerful Integers",
  "Flip Binary Tree To Match Preorder Traversal",
  "Equal Rational Numbers",
  "K Closest Points to Origin",
  "Subarray Sums Divisible by K",
  "Odd Even Jump",
  "Largest Perimeter Triangle",
  "Squares of a Sorted Array",
  "Longest Turbulent Subarray",
  "Distribute Coins in Binary Tree",
  "Unique Paths III",
  "Time Based Key-Value Store",
  "Triples with Bitwise AND Equal To Zero",
  "Minimum Cost For Tickets",
  "String Without AAA or BBB",
  "Sum of Even Numbers After Queries",
  "Interval List Intersections",
  "Vertical Order Traversal of a Binary Tree",
  "Smallest String Starting From Leaf",
  "Add to Array-Form of Integer",
  "Satisfiability of Equality Equations",
  "Broken Calculator",
  "Subarrays with K Different Integers",
  "Cousins in Binary Tree",
  "Rotting Oranges",
  "Minimum Number of K Consecutive Bit Flips",
  "Number of Squareful Arrays",
  "Find the Town Judge",
  "Maximum Binary Tree II",
  "Available Captures for Rook",
  "Minimum Cost to Merge Stones",
  "Grid Illumination",
  "Find Common Characters",
  "Check If Word Is Valid After Substitutions",
  "Max Consecutive Ones III",
  "Maximize Sum Of Array After K Negations",
  "Clumsy Factorial",
  "Minimum Domino Rotations For Equal Row",
  "Construct Binary Search Tree from Preorder Traversal",
  "Complement of Base 10 Integer",
  "Pairs of Songs With Total Durations Divisible by 60",
  "Capacity To Ship Packages Within D Days",
  "Numbers With Repeated Digits",
  "Partition Array Into Three Parts With Equal Sum",
  "Best Sightseeing Pair",
  "Smallest Integer Divisible by K",
  "Binary String With Substrings Representing 1 To N",
  "Convert to Base -2",
  "Binary Prefix Divisible By 5",
  "Next Greater Node In Linked List",
  "Number of Enclaves",
  "Remove Outermost Parentheses",
  "Sum of Root To Leaf Binary Numbers",
  "Camelcase Matching",
  "Video Stitching",
  "Divisor Game",
  "Maximum Difference Between Node and Ancestor",
  "Longest Arithmetic Subsequence",
  "Recover a Tree From Preorder Traversal",
  "Two City Scheduling",
  "Matrix Cells in Distance Order",
  "Maximum Sum of Two Non-Overlapping Subarrays",
  "Stream of Characters",
  "Moving Stones Until Consecutive",
  "Coloring A Border",
  "Uncrossed Lines",
  "Escape a Large Maze",
  "Valid Boomerang",
  "Binary Search Tree to Greater Sum Tree",
  "Minimum Score Triangulation of Polygon",
  "Moving Stones Until Consecutive II",
  "Robot Bounded In Circle",
  "Flower Planting With No Adjacent",
  "Partition Array for Maximum Sum",
  "Longest Duplicate Substring",
  "Customers Who Bought All Products",
  "Last Stone Weight",
  "Remove All Adjacent Duplicates In String",
  "Longest String Chain",
  "Last Stone Weight II",
  "Actors and Directors Who Cooperated At Least Three Times",
  "Height Checker",
  "Grumpy Bookstore Owner",
  "Previous Permutation With One Swap",
  "Distant Barcodes",
  "Shortest Way to Form String",
  "Confusing Number",
  "Campus Bikes",
  "Minimize Rounding Error to Meet Target",
  "All Paths from Source Lead to Destination",
  "Missing Element in Sorted Array",
  "Lexicographically Smallest Equivalent String",
  "Longest Repeating Substring",
  "Number of Valid Subarrays",
  "Fixed Point",
  "Index Pairs of a String",
  "Campus Bikes II",
  "Digit Count in Range",
  "Product Sales Analysis I",
  "Product Sales Analysis II",
  "Product Sales Analysis III",
  "Greatest Common Divisor of Strings",
  "Flip Columns For Maximum Number of Equal Rows",
  "Adding Two Negabinary Numbers",
  "Number of Submatrices That Sum to Target",
  "Project Employees I",
  "Project Employees II",
  "Project Employees III",
  "Occurrences After Bigram",
  "Letter Tile Possibilities",
  "Insufficient Nodes in Root to Leaf Paths",
  "Smallest Subsequence of Distinct Characters",
  "Sales Analysis I",
  "Sales Analysis II",
  "Sales Analysis III",
  "Sum of Digits in the Minimum Number",
  "High Five",
  "Brace Expansion",
  "Confusing Number II",
  "Duplicate Zeros",
  "Largest Values From Labels",
  "Shortest Path in Binary Matrix",
  "Shortest Common Supersequence",
  "Statistics from a Large Sample",
  "Car Pooling",
  "Find in Mountain Array",
  "Brace Expansion II",
  "Game Play Analysis V",
  "Unpopular Books",
  "Two Sum Less Than K",
  "Find K-Length Substrings With No Repeated Characters",
  "The Earliest Moment When Everyone Become Friends",
  "Path With Maximum Minimum Value",
  "Distribute Candies to People",
  "Path In Zigzag Labelled Binary Tree",
  "Filling Bookcase Shelves",
  "Parsing A Boolean Expression",
  "New Users Daily Count",
  "Defanging an IP Address",
  "Corporate Flight Bookings",
  "Delete Nodes And Return Forest",
  "Maximum Nesting Depth of Two Valid Parentheses Strings",
  "Highest Grade For Each Student",
  "Reported Posts",
  "Print in Order",
  "Print FooBar Alternately",
  "Print Zero Even Odd",
  "Building H2O",
  "Number of Days in a Month",
  "Remove Vowels from a String",
  "Maximum Average Subtree",
  "Divide Array Into Increasing Sequences",
  "Relative Sort Array",
  "Lowest Common Ancestor of Deepest Leaves",
  "Longest Well-Performing Interval",
  "Smallest Sufficient Team",
  "Active Businesses",
  "User Purchase Platform",
  "Number of Equivalent Domino Pairs",
  "Shortest Path with Alternating Colors",
  "Minimum Cost Tree From Leaf Values",
  "Maximum of Absolute Value Expression",
  "Reported Posts II",
  "Largest Unique Number",
  "Armstrong Number",
  "Connecting Cities With Minimum Cost",
  "Parallel Courses",
  "N-th Tribonacci Number",
  "Alphabet Board Path",
  "Largest 1-Bordered Square",
  "Stone Game II",
  "User Activity for the Past 30 Days I",
  "User Activity for the Past 30 Days II",
  "Longest Common Subsequence",
  "Decrease Elements To Make Array Zigzag",
  "Binary Tree Coloring Game",
  "Snapshot Array",
  "Longest Chunked Palindrome Decomposition",
  "Article Views I",
  "Article Views II",
  "Check If a Number Is Majority Element in a Sorted Array",
  "Minimum Swaps to Group All 1's Together",
  "Analyze User Website Visit Pattern",
  "String Transforms Into Another String",
  "Day of the Year",
  "Number of Dice Rolls With Target Sum",
  "Swap For Longest Repeated Character Substring",
  "Online Majority Element In Subarray",
  "Market Analysis I",
  "Market Analysis II",
  "Find Words That Can Be Formed by Characters",
  "Maximum Level Sum of a Binary Tree",
  "As Far from Land as Possible",
  "Last Substring in Lexicographical Order",
  "Product Price at a Given Date",
  "Single-Row Keyboard",
  "Design File System",
  "Minimum Cost to Connect Sticks",
  "Optimize Water Distribution in a Village",
  "Invalid Transactions",
  "Compare Strings by Frequency of the Smallest Character",
  "Remove Zero Sum Consecutive Nodes from Linked List",
  "Dinner Plate Stacks",
  "Immediate Food Delivery I",
  "Immediate Food Delivery II",
  "Prime Arrangements",
  "Diet Plan Performance",
  "Can Make Palindrome from Substring",
  "Number of Valid Words for Each Puzzle",
  "Reformat Department Table",
  "Count Substrings with Only One Distinct Letter",
  "Before and After Puzzle",
  "Shortest Distance to Target Color",
  "Maximum Number of Ones",
  "Distance Between Bus Stops",
  "Day of the Week",
  "Maximum Subarray Sum with One Deletion",
  "Make Array Strictly Increasing",
  "Design Bounded Blocking Queue",
  "Maximum Number of Balloons",
  "Reverse Substrings Between Each Pair of Parentheses",
  "K-Concatenation Maximum Sum",
  "Critical Connections in a Network",
  "Monthly Transactions I",
  "Tournament Winners",
  "Fizz Buzz Multithreaded",
  "How Many Apples Can You Put into the Basket",
  "Minimum Knight Moves",
  "Find Smallest Common Element in All Rows",
  "Minimum Time to Build Blocks",
  "Minimum Absolute Difference",
  "Ugly Number III",
  "Smallest String With Swaps",
  "Sort Items by Groups Respecting Dependencies",
  "Last Person to Fit in the Bus",
  "Monthly Transactions II",
  "Design Skiplist",
  "Unique Number of Occurrences",
  "Get Equal Substrings Within Budget",
  "Remove All Adjacent Duplicates in String II",
  "Minimum Moves to Reach Target with Rotations",
  "Queries Quality and Percentage",
  "Team Scores in Football Tournament",
  "Intersection of Three Sorted Arrays",
  "Two Sum BSTs",
  "Stepping Numbers",
  "Valid Palindrome III",
  "Minimum Cost to Move Chips to The Same Position",
  "Longest Arithmetic Subsequence of Given Difference",
  "Path with Maximum Gold",
  "Count Vowels Permutation",
  "Split a String in Balanced Strings",
  "Queens That Can Attack the King",
  "Dice Roll Simulation",
  "Maximum Equal Frequency",
  "Report Contiguous Dates",
  "The Dining Philosophers",
  "Airplane Seat Assignment Probability",
  "Missing Number In Arithmetic Progression",
  "Meeting Scheduler",
  "Toss Strange Coins",
  "Divide Chocolate",
  "Check If It Is a Straight Line",
  "Remove Sub-Folders from the Filesystem",
  "Replace the Substring for Balanced String",
  "Maximum Profit in Job Scheduling",
  "Web Crawler",
  "Find Positive Integer Solution for a Given Equation",
  "Circular Permutation in Binary Representation",
  "Maximum Length of a Concatenated String with Unique Characters",
  "Tiling a Rectangle with the Fewest Squares",
  "Number of Comments per Post",
  "Web Crawler Multithreaded",
  "Array Transformation",
  "Design A Leaderboard",
  "Tree Diameter",
  "Palindrome Removal",
  "Minimum Swaps to Make Strings Equal",
  "Count Number of Nice Subarrays",
  "Minimum Remove to Make Valid Parentheses",
  "Check If It Is a Good Array",
  "Encode Number",
  "Smallest Common Region",
  "Synonymous Sentences",
  "Handshakes That Don't Cross",
  "Shift 2D Grid",
  "Find Elements in a Contaminated Binary Tree",
  "Greatest Sum Divisible by Three",
  "Minimum Moves to Move a Box to Their Target Location",
  "Page Recommendations",
  "Print Immutable Linked List in Reverse",
  "Minimum Time Visiting All Points",
  "Count Servers that Communicate",
  "Search Suggestions System",
  "Number of Ways to Stay in the Same Place After Some Steps",
  "All People Report to the Given Manager",
  "Hexspeak",
  "Remove Interval",
  "Delete Tree Nodes",
  "Number of Ships in a Rectangle",
  "Find Winner on a Tic Tac Toe Game",
  "Number of Burgers with No Waste of Ingredients",
  "Count Square Submatrices with All Ones",
  "Palindrome Partitioning III",
  "Traffic Light Controlled Intersection",
  "Students and Examinations",
  "Subtract the Product and Sum of Digits of an Integer",
  "Group the People Given the Group Size They Belong To",
  "Find the Smallest Divisor Given a Threshold",
  "Minimum Number of Flips to Convert Binary Matrix to Zero Matrix",
  "Find the Start and End Number of Continuous Ranges",
  "Iterator for Combination",
  "Element Appearing More Than 25% In Sorted Array",
  "Remove Covered Intervals",
  "Minimum Falling Path Sum II",
  "Convert Binary Number in a Linked List to Integer",
  "Sequential Digits",
  "Maximum Side Length of a Square with Sum Less than or Equal to Threshold",
  "Shortest Path in a Grid with Obstacles Elimination",
  "Weather Type in Each Country",
  "Find Numbers with Even Number of Digits",
  "Divide Array in Sets of K Consecutive Numbers",
  "Maximum Number of Occurrences of a Substring",
  "Maximum Candies You Can Get from Boxes",
  "Replace Elements with Greatest Element on Right Side",
  "Sum of Mutated Array Closest to Target",
  "Deepest Leaves Sum",
  "Find the Team Size",
  "Find N Unique Integers Sum up to Zero",
  "All Elements in Two Binary Search Trees",
  "Jump Game III",
  "Verbal Arithmetic Puzzle",
  "Running Total for Different Genders",
  "Decrypt String from Alphabet to Integer Mapping",
  "XOR Queries of a Subarray",
  "Get Watched Videos by Your Friends",
  "Minimum Insertion Steps to Make a String Palindrome",
  "Decompress Run-Length Encoded List",
  "Matrix Block Sum",
  "Sum of Nodes with Even-Valued Grandparent",
  "Distinct Echo Substrings",
  "Convert Integer to the Sum of Two No-Zero Integers",
  "Minimum Flips to Make a OR b Equal to c",
  "Number of Operations to Make Network Connected",
  "Minimum Distance to Type a Word Using Two Fingers",
  "Restaurant Growth",
  "Ads Performance",
  "Maximum 69 Number",
  "Print Words Vertically",
  "Delete Leaves With a Given Value",
  "Minimum Number of Taps to Open to Water a Garden",
  "List the Products Ordered in a Period",
  "Break a Palindrome",
  "Sort the Matrix Diagonally",
  "Reverse Subarray To Maximize Array Value",
  "Rank Transform of an Array",
  "Remove Palindromic Subsequences",
  "Filter Restaurants by Vegan-Friendly, Price and Distance",
  "Find the City With the Smallest Number of Neighbors at a Threshold Distance",
  "Minimum Difficulty of a Job Schedule",
  "Number of Transactions per Visit",
  "The K Weakest Rows in a Matrix",
  "Reduce Array Size to The Half",
  "Maximum Product of Splitted Binary Tree",
  "Jump Game V",
  "Movie Rating",
  "Number of Steps to Reduce a Number to Zero",
  "Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold",
  "Angle Between Hands of a Clock",
  "Jump Game IV",
  "Check If N and Its Double Exist",
  "Minimum Number of Steps to Make Two Strings Anagram",
  "Tweet Counts Per Frequency",
  "Maximum Students Taking Exam",
  "Students With Invalid Departments",
  "Count Negative Numbers in a Sorted Matrix",
  "Product of the Last K Numbers",
  "Maximum Number of Events That Can Be Attended",
  "Construct Target Array With Multiple Sums",
  "Activity Participants",
  "Sort Integers by The Number of 1 Bits",
  "Apply Discount Every n Orders",
  "Number of Substrings Containing All Three Characters",
  "Count All Valid Pickup and Delivery Options",
  "Number of Days Between Two Dates",
  "Validate Binary Tree Nodes",
  "Closest Divisors",
  "Largest Multiple of Three",
  "Number of Trusted Contacts of a Customer",
  "How Many Numbers Are Smaller Than the Current Number",
  "Rank Teams by Votes",
  "Linked List in Binary Tree",
  "Minimum Cost to Make at Least One Valid Path in a Grid",
  "Get the Second Most Recent Activity",
  "Increasing Decreasing String",
  "Find the Longest Substring Containing Vowels in Even Counts",
  "Longest ZigZag Path in a Binary Tree",
  "Maximum Sum BST in Binary Tree",
  "Generate a String With Characters That Have Odd Counts",
  "Number of Times Binary String Is Prefix-Aligned",
  "Time Needed to Inform All Employees",
  "Frog Position After T Seconds",
  "Replace Employee ID With The Unique Identifier",
  "Find a Corresponding Node of a Binary Tree in a Clone of That Tree",
  "Lucky Numbers in a Matrix",
  "Design a Stack With Increment Operation",
  "Balance a Binary Search Tree",
  "Maximum Performance of a Team",
  "Total Sales Amount by Year",
  "Find the Distance Value Between Two Arrays",
  "Cinema Seat Allocation",
  "Sort Integers by The Power Value",
  "Pizza With 3n Slices",
  "Create Target Array in the Given Order",
  "Four Divisors",
  "Check if There is a Valid Path in a Grid",
  "Longest Happy Prefix",
  "Capital Gain/Loss",
  "Find Lucky Integer in an Array",
  "Count Number of Teams",
  "Design Underground System",
  "Find All Good Strings",
  "Customers Who Bought Products A and B but Not C",
  "Count Largest Group",
  "Construct K Palindrome Strings",
  "Circle and Rectangle Overlapping",
  "Reducing Dishes",
  "Minimum Subsequence in Non-Increasing Order",
  "Number of Steps to Reduce a Number in Binary Representation to One",
  "Longest Happy String",
  "Stone Game III",
  "Top Travellers",
  "String Matching in an Array",
  "Queries on a Permutation With Key",
  "HTML Entity Parser",
  "Number of Ways to Paint N × 3 Grid",
  "Find the Quiet Students in All Exams",
  "Minimum Value to Get Positive Step by Step Sum",
  "Find the Minimum Number of Fibonacci Numbers Whose Sum Is K",
  "The k-th Lexicographical String of All Happy Strings of Length n",
  "Restore The Array",
  "Reformat The String",
  "Display Table of Food Orders in a Restaurant",
  "Minimum Number of Frogs Croaking",
  "Build Array Where You Can Find The Maximum Exactly K Comparisons",
  "NPV Queries",
  "Maximum Score After Splitting a String",
  "Maximum Points You Can Obtain from Cards",
  "Diagonal Traverse II",
  "Constrained Subsequence Sum",
  "Counting Elements",
  "Perform String Shifts",
  "Leftmost Column with at Least a One",
  "First Unique Number",
  "Check If a String Is a Valid Sequence from Root to Leaves Path in a Binary Tree",
  "Kids With the Greatest Number of Candies",
  "Max Difference You Can Get From Changing an Integer",
  "Check If a String Can Break Another String",
  "Number of Ways to Wear Different Hats to Each Other",
  "Create a Session Bar Chart",
  "Destination City",
  "Check If All 1's Are at Least Length K Places Away",
  "Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit",
  "Find the Kth Smallest Sum of a Matrix With Sorted Rows",
  "Evaluate Boolean Expression",
  "Build an Array With Stack Operations",
  "Count Triplets That Can Form Two Arrays of Equal XOR",
  "Minimum Time to Collect All Apples in a Tree",
  "Number of Ways of Cutting a Pizza",
  "Apples & Oranges",
  "Consecutive Characters",
  "Simplified Fractions",
  "Count Good Nodes in Binary Tree",
  "Form Largest Integer With Digits That Add up to Target",
  "Number of Students Doing Homework at a Given Time",
  "Rearrange Words in a Sentence",
  "People Whose List of Favorite Companies Is Not a Subset of Another List",
  "Maximum Number of Darts Inside of a Circular Dartboard",
  "Active Users",
  "Check If a Word Occurs As a Prefix of Any Word in a Sentence",
  "Maximum Number of Vowels in a Substring of Given Length",
  "Pseudo-Palindromic Paths in a Binary Tree",
  "Max Dot Product of Two Subsequences",
  "Rectangles Area",
  "Make Two Arrays Equal by Reversing Subarrays",
  "Check If a String Contains All Binary Codes of Size K",
  "Course Schedule IV",
  "Cherry Pickup II",
  "Maximum Product of Two Elements in an Array",
  "Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts",
  "Reorder Routes to Make All Paths Lead to the City Zero",
  "Probability of a Two Boxes Having The Same Number of Distinct Balls",
  "Calculate Salaries",
  "Find All The Lonely Nodes",
  "Shuffle the Array",
  "The k Strongest Values in an Array",
  "Design Browser History",
  "Paint House III",
  "Delete N Nodes After M Nodes of a Linked List",
  "Final Prices With a Special Discount in a Shop",
  "Subrectangle Queries",
  "Find Two Non-overlapping Sub-arrays Each With Target Sum",
  "Allocate Mailboxes",
  "Sales by Day of the Week",
  "Running Sum of 1d Array",
  "Least Number of Unique Integers after K Removals",
  "Minimum Number of Days to Make m Bouquets",
  "Kth Ancestor of a Tree Node",
  "Group Sold Products By The Date",
  "Clone Binary Tree With Random Pointer",
  "XOR Operation in an Array",
  "Making File Names Unique",
  "Avoid Flood in The City",
  "Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree",
  "Clone N-ary Tree",
  "Average Salary Excluding the Minimum and Maximum Salary",
  "The kth Factor of n",
  "Longest Subarray of 1's After Deleting One Element",
  "Parallel Courses II",
  "Friendly Movies Streamed Last Month",
  "Path Crossing",
  "Check If Array Pairs Are Divisible by k",
  "Number of Subsequences That Satisfy the Given Sum Condition",
  "Max Value of Equation",
  "Design a File Sharing System",
  "Countries You Can Safely Invest In",
  "Can Make Arithmetic Progression From Sequence",
  "Last Moment Before All Ants Fall Out of a Plank",
  "Count Submatrices With All Ones",
  "Minimum Possible Integer After at Most K Adjacent Swaps On Digits",
  "Find Root of N-Ary Tree",
  "Reformat Date",
  "Range Sum of Sorted Subarray Sums",
  "Minimum Difference Between Largest and Smallest Value in Three Moves",
  "Stone Game IV",
  "Customer Order Frequency",
  "Number of Good Pairs",
  "Number of Substrings With Only 1s",
  "Path with Maximum Probability",
  "Best Position for a Service Centre",
  "Move Sub-Tree of N-Ary Tree",
  "Find Users With Valid E-Mails",
  "Water Bottles",
  "Number of Nodes in the Sub-Tree With the Same Label",
  "Maximum Number of Non-Overlapping Substrings",
  "Find a Value of a Mysterious Function Closest to Target",
  "Diameter of N-Ary Tree",
  "Count Odd Numbers in an Interval Range",
  "Number of Sub-arrays With Odd Sum",
  "Number of Good Ways to Split a String",
  "Minimum Number of Increments on Subarrays to Form a Target Array",
  "Patients With a Condition",
  "Shuffle String",
  "Minimum Suffix Flips",
  "Number of Good Leaf Nodes Pairs",
  "String Compression II",
  "The Most Recent Three Orders",
  "Find the Index of the Large Integer",
  "Count Good Triplets",
  "Find the Winner of an Array Game",
  "Minimum Swaps to Arrange a Binary Grid",
  "Get the Maximum Score",
  "Guess the Majority in a Hidden Array",
  "Kth Missing Positive Number",
  "Can Convert String in K Moves",
  "Minimum Insertions to Balance a Parentheses String",
  "Find Longest Awesome Substring",
  "Fix Product Name Format",
  "Make The String Great",
  "Find Kth Bit in Nth Binary String",
  "Maximum Number of Non-Overlapping Subarrays With Sum Equals Target",
  "Minimum Cost to Cut a Stick",
  "The Most Similar Path in a Graph",
  "The Most Recent Orders for Each Product",
  "Three Consecutive Odds",
  "Minimum Operations to Make Array Equal",
  "Magnetic Force Between Two Balls",
  "Minimum Number of Days to Eat N Oranges",
  "Strings Differ by One Character",
  "Bank Account Summary",
  "Thousand Separator",
  "Minimum Number of Vertices to Reach All Nodes",
  "Minimum Numbers of Function Calls to Make Target Array",
  "Detect Cycles in 2D Grid",
  "Most Visited Sector in a Circular Track",
  "Maximum Number of Coins You Can Get",
  "Find Latest Group of Size M",
  "Stone Game V",
  "Put Boxes Into the Warehouse I",
  "Unique Orders and Customers Per Month",
  "Detect Pattern of Length M Repeated K or More Times",
  "Maximum Length of Subarray With Positive Product",
  "Minimum Number of Days to Disconnect Island",
  "Number of Ways to Reorder Array to Get Same BST",
  "Dot Product of Two Sparse Vectors",
  "Warehouse Manager",
  "Matrix Diagonal Sum",
  "Number of Ways to Split a String",
  "Shortest Subarray to be Removed to Make Array Sorted",
  "Count All Possible Routes",
  "Replace All ?'s to Avoid Consecutive Repeating Characters",
  "Number of Ways Where Square of Number Is Equal to Product of Two Numbers",
  "Minimum Time to Make Rope Colorful",
  "Remove Max Number of Edges to Keep Graph Fully Traversable",
  "Put Boxes Into the Warehouse II",
  "Customer Who Visited but Did Not Make Any Transactions",
  "Special Positions in a Binary Matrix",
  "Count Unhappy Friends",
  "Min Cost to Connect All Points",
  "Check If String Is Transformable With Substring Sort Operations",
  "Binary Search Tree Iterator II",
  "Bank Account Summary II",
  "Sum of All Odd Length Subarrays",
  "Maximum Sum Obtained of Any Permutation",
  "Make Sum Divisible by P",
  "Strange Printer II",
  "Rearrange Spaces Between Words",
  "Split a String Into the Max Number of Unique Substrings",
  "Maximum Non Negative Product in a Matrix",
  "Minimum Cost to Connect Two Groups of Points",
  "The Most Frequently Ordered Products for Each Customer",
  "Build Binary Expression Tree From Infix Expression",
  "Crawler Log Folder",
  "Maximum Profit of Operating a Centennial Wheel",
  "Throne Inheritance",
  "Maximum Number of Achievable Transfer Requests",
  "Find Nearest Right Node in Binary Tree",
  "Design Parking System",
  "Alert Using Same Key-Card Three or More Times in a One Hour Period",
  "Find Valid Matrix Given Row and Column Sums",
  "Find Servers That Handled Most Number of Requests",
  "Sellers With No Sales",
  "Special Array With X Elements Greater Than or Equal X",
  "Even Odd Tree",
  "Maximum Number of Visible Points",
  "Minimum One Bit Operations to Make Integers Zero",
  "Check If Two Expression Trees are Equivalent",
  "Find the Missing IDs",
  "Maximum Nesting Depth of the Parentheses",
  "Maximal Network Rank",
  "Split Two Strings to Make Palindrome",
  "Count Subtrees With Max Distance Between Cities",
  "Maximum Font to Fit a Sentence in a Screen",
  "Mean of Array After Removing Some Elements",
  "Coordinate With Maximum Network Quality",
  "Number of Sets of K Non-Overlapping Line Segments",
  "Fancy Sequence",
  "All Valid Triplets That Can Represent a Country",
  "Largest Substring Between Two Equal Characters",
  "Lexicographically Smallest String After Applying Operations",
  "Best Team With No Conflicts",
  "Graph Connectivity With Threshold",
  "Design an Expression Tree With Evaluate Function",
  "Slowest Key",
  "Arithmetic Subarrays",
  "Path With Minimum Effort",
  "Rank Transform of a Matrix",
  "Percentage of Users Attended a Contest",
  "Add Two Polynomials Represented as Linked Lists",
  "Hopper Company Queries I",
  "Sort Array by Increasing Frequency",
  "Widest Vertical Area Between Two Points Containing No Points",
  "Count Substrings That Differ by One Character",
  "Number of Ways to Form a Target String Given a Dictionary",
  "Check Array Formation Through Concatenation",
  "Count Sorted Vowel Strings",
  "Furthest Building You Can Reach",
  "Kth Smallest Instructions",
  "Lowest Common Ancestor of a Binary Tree II",
  "Hopper Company Queries II",
  "Get Maximum in Generated Array",
  "Minimum Deletions to Make Character Frequencies Unique",
  "Sell Diminishing-Valued Colored Balls",
  "Create Sorted Array through Instructions",
  "Lowest Common Ancestor of a Binary Tree III",
  "Hopper Company Queries III",
  "Defuse the Bomb",
  "Minimum Deletions to Make String Balanced",
  "Minimum Jumps to Reach Home",
  "Distribute Repeating Integers",
  "Design an Ordered Stream",
  "Determine if Two Strings Are Close",
  "Minimum Operations to Reduce X to Zero",
  "Maximize Grid Happiness",
  "Correct a Binary Tree",
  "Average Time of Process per Machine",
  "Check If Two String Arrays are Equivalent",
  "Smallest String With A Given Numeric Value",
  "Ways to Make a Fair Array",
  "Minimum Initial Energy to Finish Tasks",
  "Change the Root of a Binary Tree",
  "Fix Names in a Table",
  "Maximum Repeating Substring",
  "Merge In Between Linked Lists",
  "Design Front Middle Back Queue",
  "Minimum Number of Removals to Make Mountain Array",
  "Richest Customer Wealth",
  "Find the Most Competitive Subsequence",
  "Minimum Moves to Make Array Complementary",
  "Minimize Deviation in Array",
  "Lowest Common Ancestor of a Binary Tree IV",
  "Product's Worth Over Invoices",
  "Goal Parser Interpretation",
  "Max Number of K-Sum Pairs",
  "Concatenation of Consecutive Binary Numbers",
  "Minimum Incompatibility",
  "Longest Palindromic Subsequence II",
  "Invalid Tweets",
  "Count the Number of Consistent Strings",
  "Sum of Absolute Differences in a Sorted Array",
  "Stone Game VI",
  "Delivering Boxes from Storage to Ports",
  "Count of Matches in Tournament",
  "Partitioning Into Minimum Number Of Deci-Binary Numbers",
  "Stone Game VII",
  "Maximum Height by Stacking Cuboids",
  "Count Ways to Distribute Candies",
  "Daily Leads and Partners",
  "Reformat Phone Number",
  "Maximum Erasure Value",
  "Jump Game VI",
  "Checking Existence of Edge Length Limited Paths",
  "Number of Distinct Substrings in a String",
  "Number of Calls Between Two Persons",
  "Number of Students Unable to Eat Lunch",
  "Average Waiting Time",
  "Maximum Binary String After Change",
  "Minimum Adjacent Swaps for K Consecutive Ones",
  "Determine if String Halves Are Alike",
  "Maximum Number of Eaten Apples",
  "Where Will the Ball Fall",
  "Maximum XOR With an Element From Array",
  "Largest Subarray Length K",
  "Biggest Window Between Visits",
  "Maximum Units on a Truck",
  "Count Good Meals",
  "Ways to Split Array Into Three Subarrays",
  "Minimum Operations to Make a Subsequence",
  "Sum Of Special Evenly-Spaced Elements In Array",
  "Count Apples and Oranges",
  "Calculate Money in Leetcode Bank",
  "Maximum Score From Removing Substrings",
  "Construct the Lexicographically Largest Valid Sequence",
  "Number Of Ways To Reconstruct A Tree",
  "Decode XORed Array",
  "Swapping Nodes in a Linked List",
  "Minimize Hamming Distance After Swap Operations",
  "Find Minimum Time to Finish All Jobs",
  "Checking Existence of Edge Length Limited Paths II",
  "Number Of Rectangles That Can Form The Largest Square",
  "Tuple with Same Product",
  "Largest Submatrix With Rearrangements",
  "Cat and Mouse II",
  "Find Followers Count",
  "Shortest Path to Get Food",
  "The Number of Employees Which Report to Each Employee",
  "Find the Highest Altitude",
  "Minimum Number of People to Teach",
  "Decode XORed Permutation",
  "Count Ways to Make Array With Product",
  "Latest Time by Replacing Hidden Digits",
  "Change Minimum Characters to Satisfy One of Three Conditions",
  "Find Kth Largest XOR Coordinate Value",
  "Building Boxes",
  "Find Distance in a Binary Tree",
  "Find Total Time Spent by Each Employee",
  "Maximum Number of Balls in a Box",
  "Restore the Array From Adjacent Pairs",
  "Can You Eat Your Favorite Candy on Your Favorite Day?",
  "Palindrome Partitioning IV",
  "Maximum Subarray Sum After One Operation",
  "Leetflex Banned Accounts",
  "Sum of Unique Elements",
  "Maximum Absolute Sum of Any Subarray",
  "Minimum Length of String After Deleting Similar Ends",
  "Maximum Number of Events That Can Be Attended II",
  "Check if Array Is Sorted and Rotated",
  "Maximum Score From Removing Stones",
  "Largest Merge Of Two Strings",
  "Closest Subsequence Sum",
  "Design Most Recently Used Queue",
  "Recyclable and Low Fat Products",
  "Minimum Changes To Make Alternating Binary String",
  "Count Number of Homogenous Substrings",
  "Minimum Limit of Balls in a Bag",
  "Minimum Degree of a Connected Trio in a Graph",
  "Buildings With an Ocean View",
  "Longest Nice Substring",
  "Form Array by Concatenating Subarrays of Another Array",
  "Map of Highest Peak",
  "Tree of Coprimes",
  "Find the Subtasks That Did Not Execute",
  "Merge Strings Alternately",
  "Minimum Number of Operations to Move All Balls to Each Box",
  "Maximum Score from Performing Multiplication Operations",
  "Maximize Palindrome Length From Subsequences",
  "Sort Features by Popularity",
  "Count Items Matching a Rule",
  "Closest Dessert Cost",
  "Equal Sum Arrays With Minimum Number of Operations",
  "Car Fleet II",
  "Product's Price for Each Store",
  "Shortest Path in a Hidden Grid",
  "Find Nearest Point That Has the Same X or Y Coordinate",
  "Check if Number is a Sum of Powers of Three",
  "Sum of Beauty of All Substrings",
  "Count Pairs Of Nodes",
  "Grand Slam Titles",
  "Check if Binary String Has at Most One Segment of Ones",
  "Minimum Elements to Add to Form a Given Sum",
  "Number of Restricted Paths From First to Last Node",
  "Make the XOR of All Segments Equal to Zero",
  "Maximize the Beauty of the Garden",
  "Primary Department for Each Employee",
  "Check if One String Swap Can Make Strings Equal",
  "Find Center of Star Graph",
  "Maximum Average Pass Ratio",
  "Maximum Score of a Good Subarray",
  "Count Pairs of Equal Substrings With Minimum Difference",
  "Rearrange Products Table",
  "Second Largest Digit in a String",
  "Design Authentication Manager",
  "Maximum Number of Consecutive Values You Can Make",
  "Maximize Score After N Operations",
  "Maximum Ascending Subarray Sum",
  "Number of Orders in the Backlog",
  "Maximum Value at a Given Index in a Bounded Array",
  "Count Pairs With XOR in a Range",
  "Implement Trie II (Prefix Tree)",
  "Number of Different Integers in a String",
  "Minimum Number of Operations to Reinitialize a Permutation",
  "Evaluate the Bracket Pairs of a String",
  "Maximize Number of Nice Divisors",
  "Ad-Free Sessions",
  "Minimum Path Cost in a Hidden Grid",
  "Find Interview Candidates",
  "Determine Color of a Chessboard Square",
  "Sentence Similarity III",
  "Count Nice Pairs in an Array",
  "Maximum Number of Groups Getting Fresh Donuts",
  "Truncate Sentence",
  "Finding the Users Active Minutes",
  "Minimum Absolute Sum Difference",
  "Number of Different Subsequences GCDs",
  "Maximum Number of Accepted Invitations",
  "Find Customers With Positive Revenue this Year",
  "Sign of the Product of an Array",
  "Find the Winner of the Circular Game",
  "Minimum Sideway Jumps",
  "Finding MK Average",
  "Faulty Sensor",
  "Minimum Operations to Make the Array Increasing",
  "Queries on Number of Points Inside a Circle",
  "Maximum XOR for Each Query",
  "Minimum Number of Operations to Make String Sorted",
  "Maximum Transaction Each Day",
  "Check if the Sentence Is Pangram",
  "Maximum Ice Cream Bars",
  "Single-Threaded CPU",
  "Find XOR Sum of All Pairs Bitwise AND",
  "Remove Duplicates From an Unsorted Linked List",
  "Sum of Digits in Base K",
  "Frequency of the Most Frequent Element",
  "Longest Substring Of All Vowels in Order",
  "Maximum Building Height",
  "League Statistics",
  "Next Palindrome Using Same Digits",
  "Suspicious Bank Accounts",
  "Replace All Digits with Characters",
  "Seat Reservation Manager",
  "Maximum Element After Decreasing and Rearranging",
  "Closest Room",
  "Minimum Distance to the Target Element",
  "Splitting a String Into Descending Consecutive Values",
  "Minimum Adjacent Swaps to Reach the Kth Smallest Number",
  "Minimum Interval to Include Each Query",
  "Distinct Numbers in Each Subarray",
  "Convert Date Format",
  "Maximum Population Year",
  "Maximum Distance Between a Pair of Values",
  "Maximum Subarray Min-Product",
  "Largest Color Value in a Directed Graph",
  "Longest Word With All Prefixes",
  "Sorting the Sentence",
  "Incremental Memory Leak",
  "Rotating the Box",
  "Sum of Floored Pairs",
  "Sum of All Subset XOR Totals",
  "Minimum Number of Swaps to Make the Binary String Alternating",
  "Finding Pairs With a Certain Sum",
  "Number of Ways to Rearrange Sticks With K Sticks Visible",
  "Orders With Maximum Quantity Above Average",
  "Product of Two Run-Length Encoded Arrays",
  "Longer Contiguous Segments of Ones than Zeros",
  "Minimum Speed to Arrive on Time",
  "Jump Game VII",
  "Stone Game VIII",
  "Calculate Special Bonus",
  "Minimize Product Sum of Two Arrays",
  "Group Employees of the Same Salary",
  "Substrings of Size Three with Distinct Characters",
  "Minimize Maximum Pair Sum in Array",
  "Get Biggest Three Rhombus Sums in a Grid",
  "Minimum XOR Sum of Two Arrays",
  "Check if Word Equals Summation of Two Words",
  "Maximum Value after Insertion",
  "Process Tasks Using Servers",
  "Minimum Skips to Arrive at Meeting On Time",
  "Egg Drop With 2 Eggs and N Floors",
  "Count Pairs in Two Arrays",
  "Determine Whether Matrix Can Be Obtained By Rotation",
  "Reduction Operations to Make the Array Elements Equal",
  "Minimum Number of Flips to Make the Binary String Alternating",
  "Minimum Space Wasted From Packaging",
  "The Latest Login in 2020",
  "Cutting Ribbons",
  "Page Recommendations II",
  "Check if All the Integers in a Range Are Covered",
  "Find the Student that Will Replace the Chalk",
  "Largest Magic Square",
  "Minimum Cost to Change the Final Value of Expression",
  "Redistribute Characters to Make All Strings Equal",
  "Maximum Number of Removable Characters",
  "Merge Triplets to Form Target Triplet",
  "The Earliest and Latest Rounds Where Players Compete",
  "Find a Peak Element II",
  "Depth of BST Given Insertion Order",
  "Largest Odd Number in String",
  "The Number of Full Rounds You Have Played",
  "Count Sub Islands",
  "Minimum Absolute Difference Queries",
  "Count Salary Categories",
  "Game of Nim",
  "Remove One Element to Make the Array Strictly Increasing",
  "Remove All Occurrences of a Substring",
  "Maximum Alternating Subsequence Sum",
  "Design Movie Rental System",
  "Maximum Product Difference Between Two Pairs",
  "Cyclically Rotating a Grid",
  "Number of Wonderful Substrings",
  "Count Ways to Build Rooms in an Ant Colony",
  "Leetcodify Friends Recommendations",
  "Kth Smallest Subarray Sum",
  "Leetcodify Similar Friends",
  "Build Array from Permutation",
  "Eliminate Maximum Number of Monsters",
  "Count Good Numbers",
  "Longest Common Subpath",
  "Erect the Fence II",
  "Count Square Sum Triples",
  "Nearest Exit from Entrance in Maze",
  "Sum Game",
  "Minimum Cost to Reach Destination in Time",
  "Concatenation of Array",
  "Unique Length-3 Palindromic Subsequences",
  "Painting a Grid With Three Different Colors",
  "Merge BSTs to Create Single BST",
  "Check if String Is Decomposable Into Value-Equal Substrings",
  "Confirmation Rate",
  "Maximum Number of Words You Can Type",
  "Add Minimum Number of Rungs",
  "Maximum Number of Points with Cost",
  "Maximum Genetic Difference Query",
  "Users That Actively Request Confirmation Messages",
  "Longest Common Subsequence Between Sorted Arrays",
  "Check if All Characters Have Equal Number of Occurrences",
  "The Number of the Smallest Unoccupied Chair",
  "Describe the Painting",
  "Number of Visible People in a Queue",
  "Sum of Digits of String After Convert",
  "Largest Number After Mutating Substring",
  "Maximum Compatibility Score Sum",
  "Delete Duplicate Folders in System",
  "Strong Friendship",
  "Maximum of Minimum Values in All Subarrays",
  "All the Pairs With the Maximum Number of Common Followers",
  "Three Divisors",
  "Maximum Number of Weeks for Which You Can Work",
  "Minimum Garden Perimeter to Collect Enough Apples",
  "Count Number of Special Subsequences",
  "Minimum Time For K Virus Variants to Spread",
  "Delete Characters to Make Fancy String",
  "Check if Move is Legal",
  "Minimum Total Space Wasted With K Resizing Operations",
  "Maximum Product of the Length of Two Palindromic Substrings",
  "Check If String Is a Prefix of Array",
  "Remove Stones to Minimize the Total",
  "Minimum Number of Swaps to Make the String Balanced",
  "Find the Longest Valid Obstacle Course at Each Position",
  "Employees With Missing Information",
  "Binary Searchable Numbers in an Unsorted Array",
  "Number of Strings That Appear as Substrings in Word",
  "Array With Elements Not Equal to Average of Neighbors",
  "Minimum Non-Zero Product of the Array Elements",
  "Last Day Where You Can Still Cross",
  "Find if Path Exists in Graph",
  "First and Last Call On the Same Day",
  "Count Nodes Equal to Sum of Descendants",
  "Minimum Time to Type Word Using Special Typewriter",
  "Maximum Matrix Sum",
  "Number of Ways to Arrive at Destination",
  "Number of Ways to Separate Numbers",
  "Employees Whose Manager Left the Company",
  "Find Greatest Common Divisor of Array",
  "Find Unique Binary String",
  "Minimize the Difference Between Target and Chosen Elements",
  "Find Array Given Subset Sums",
  "Widest Pair of Indices With Equal Range Sum",
  "Minimum Difference Between Highest and Lowest of K Scores",
  "Find the Kth Largest Integer in the Array",
  "Minimum Number of Work Sessions to Finish the Tasks",
  "Number of Unique Good Subsequences",
  "Find Cutoff Score for Each School",
  "Maximum Number of People That Can Be Caught in Tag",
  "Count the Number of Experiments",
  "Find the Middle Index in Array",
  "Find All Groups of Farmland",
  "Operations on Tree",
  "The Number of Good Subsets",
  "Count Special Quadruplets",
  "The Number of Weak Characters in the Game",
  "First Day Where You Have Been in All the Rooms",
  "GCD Sort of an Array",
  "Smallest Greater Multiple Made of Two Digits",
  "Reverse Prefix of Word",
  "Maximum Product of the Length of Two Palindromic Subsequences",
  "Smallest Missing Genetic Value in Each Subtree",
  "The Number of Seniors and Juniors to Join the Company",
  "Subtree Removal Game with Fibonacci Tree",
  "Count Number of Pairs With Absolute Difference K",
  "Find Original Array From Doubled Array",
  "Maximum Earnings From Taxi",
  "Minimum Number of Operations to Make Array Continuous",
  "The Number of Seniors and Juniors to Join the Company II",
  "Final Value of Variable After Performing Operations",
  "Sum of Beauty in the Array",
  "Detect Squares",
  "Longest Subsequence Repeated k Times",
  "Average Height of Buildings in Each Segment",
  "Maximum Difference Between Increasing Elements",
  "Grid Game",
  "Check if Word Can Be Placed In Crossword",
  "The Score of Students Solving Math Expression",
  "Number of Accounts That Did Not Stream",
  "Brightest Position on Street",
  "Convert 1D Array Into 2D Array",
  "Number of Pairs of Strings With Concatenation Equal to Target",
  "Maximize the Confusion of an Exam",
  "Maximum Number of Ways to Partition an Array",
  "Low-Quality Problems",
  "Minimum Moves to Convert String",
  "Find Missing Observations",
  "Stone Game IX",
  "Smallest K-Length Subsequence With Occurrences of a Letter",
  "Count Subarrays With More Ones Than Zeros",
  "Two Out of Three",
  "Minimum Operations to Make a Uni-Value Grid",
  "Stock Price Fluctuation",
  "Partition Array Into Two Arrays to Minimize Sum Difference",
  "Maximum Alternating Subarray Sum",
  "Minimum Number of Moves to Seat Everyone",
  "Remove Colored Pieces if Both Neighbors are the Same Color",
  "The Time When the Network Becomes Idle",
  "Kth Smallest Product of Two Sorted Arrays",
  "Accepted Candidates From the Interviews",
  "Check if Numbers Are Ascending in a Sentence",
  "Simple Bank System",
  "Count Number of Maximum Bitwise-OR Subsets",
  "Second Minimum Time to Reach Destination",
  "Sort Linked List Already Sorted Using Absolute Values",
  "Number of Valid Words in a Sentence",
  "Next Greater Numerically Balanced Number",
  "Count Nodes With the Highest Score",
  "Parallel Courses III",
  "The Category of Each Member in the Store",
  "Minimum Cost to Separate Sentence Into Rows",
  "Kth Distinct String in an Array",
  "Two Best Non-Overlapping Events",
  "Plates Between Candles",
  "Number of Valid Move Combinations On Chessboard",
  "Smallest Index With Equal Value",
  "Find the Minimum and Maximum Number of Nodes Between Critical Points",
  "Minimum Operations to Convert Number",
  "Check if an Original String Exists Given Two Encoded Strings",
  "Number of Spaces Cleaning Robot Cleaned",
  "Count Vowel Substrings of a String",
  "Vowels of All Substrings",
  "Minimized Maximum of Products Distributed to Any Store",
  "Maximum Path Quality of a Graph",
  "Account Balance",
  "Number of Equal Count Substrings",
  "Check Whether Two Strings are Almost Equivalent",
  "Walking Robot Simulation II",
  "Most Beautiful Item for Each Query",
  "Maximum Number of Tasks You Can Assign",
  "The Winner University",
  "Time Needed to Buy Tickets",
  "Reverse Nodes in Even Length Groups",
  "Decode the Slanted Ciphertext",
  "Process Restricted Friend Requests",
  "Paths in Maze That Lead to Same Room",
  "Two Furthest Houses With Different Colors",
  "Watering Plants",
  "Range Frequency Queries",
  "Sum of k-Mirror Numbers",
  "The Number of Rich Customers",
  "Substrings That Begin and End With the Same Letter",
  "Drop Type 1 Orders for Customers With Type 0 Orders",
  "Count Common Words With One Occurrence",
  "Minimum Number of Food Buckets to Feed the Hamsters",
  "Minimum Cost Homecoming of a Robot in a Grid",
  "Count Fertile Pyramids in a Land",
  "Find Target Indices After Sorting Array",
  "K Radius Subarray Averages",
  "Removing Minimum and Maximum From Array",
  "Find All People With Secret",
  "Minimum Cost to Reach City With Discounts",
  "Finding 3-Digit Even Numbers",
  "Delete the Middle Node of a Linked List",
  "Step-By-Step Directions From a Binary Tree Node to Another",
  "Valid Arrangement of Pairs",
  "Subsequence of Size K With the Largest Even Sum",
  "Find Subsequence of Length K With the Largest Sum",
  "Find Good Days to Rob the Bank",
  "Detonate the Maximum Bombs",
  "Sequentially Ordinal Rank Tracker",
  "Rings and Rods",
  "Sum of Subarray Ranges",
  "Watering Plants II",
  "Maximum Fruits Harvested After at Most K Steps",
  "Number of Unique Flavors After Sharing K Candies",
  "Find First Palindromic String in the Array",
  "Adding Spaces to a String",
  "Number of Smooth Descent Periods of a Stock",
  "Minimum Operations to Make the Array K-Increasing",
  "The Airport With the Most Traffic",
  "Elements in Array After Removing and Replacing Elements",
  "Maximum Number of Words Found in Sentences",
  "Find All Possible Recipes from Given Supplies",
  "Check if a Parentheses String Can Be Valid",
  "Abbreviating the Product of a Range",
  "Build the Equation",
  "A Number After a Double Reversal",
  "Execution of All Suffix Instructions Staying in a Grid",
  "Intervals Between Identical Elements",
  "Recover the Original Array",
  "Minimum Operations to Remove Adjacent Ones in Matrix",
  "Check if All A's Appears Before All B's",
  "Number of Laser Beams in a Bank",
  "Destroying Asteroids",
  "Maximum Employees to Be Invited to a Meeting",
  "Remove All Ones With Row and Column Flips",
  "Capitalize the Title",
  "Maximum Twin Sum of a Linked List",
  "Longest Palindrome by Concatenating Two Letter Words",
  "Stamping the Grid",
  "Check if Every Row and Column Contains All Numbers",
  "Minimum Swaps to Group All 1's Together II",
  "Count Words Obtained After Adding a Letter",
  "Earliest Possible Day of Full Bloom",
  "Pour Water Between Buckets to Make Water Levels Equal",
  "Divide a String Into Groups of Size k",
  "Minimum Moves to Reach Target Score",
  "Solving Questions With Brainpower",
  "Maximum Running Time of N Computers",
  "The Number of Passengers in Each Bus I",
  "Choose Numbers From Two Arrays in Range",
  "Minimum Cost of Buying Candies With Discount",
  "Count the Hidden Sequences",
  "K Highest Ranked Items Within a Price Range",
  "Number of Ways to Divide a Long Corridor",
  "Count Elements With Strictly Smaller and Greater Elements",
  "Rearrange Array Elements by Sign",
  "Find All Lonely Numbers in the Array",
  "Maximum Good People Based on Statements",
  "Minimum Number of Lines to Cover Points",
  "The Number of Passengers in Each Bus II",
  "Keep Multiplying Found Values by Two",
  "All Divisions With the Highest Score of a Binary Array",
  "Find Substring With Given Hash Value",
  "Groups of Strings",
  "Amount of New Area Painted Each Day",
  "Order Two Columns Independently",
  "Minimum Sum of Four Digit Number After Splitting Digits",
  "Partition Array According to Given Pivot",
  "Minimum Cost to Set Cooking Time",
  "Minimum Difference in Sums After Removal of Elements",
  "Sort Even and Odd Indices Independently",
  "Smallest Value of the Rearranged Number",
  "Design Bitset",
  "Minimum Time to Remove All Cars Containing Illegal Goods",
  "Unique Substrings With Equal Digit Frequency",
  "Count Operations to Obtain Zero",
  "Minimum Operations to Make the Array Alternating",
  "Removing Minimum Number of Magic Beans",
  "Maximum AND Sum of Array",
  "Longest Winning Streak",
  "Remove All Ones With Row and Column Flips II",
  "The Change in Global Rankings",
  "Count Equal and Divisible Pairs in an Array",
  "Find Three Consecutive Integers That Sum to a Given Number",
  "Maximum Split of Positive Even Integers",
  "Count Good Triplets in an Array",
  "Count Integers With Even Digit Sum",
  "Merge Nodes in Between Zeros",
  "Construct String With Repeat Limit",
  "Count Array Pairs Divisible by K",
  "Number of Ways to Build Sturdy Brick Wall",
  "Counting Words With a Given Prefix",
  "Minimum Number of Steps to Make Two Strings Anagram II",
  "Minimum Time to Complete Trips",
  "Minimum Time to Finish the Race",
  "Number of Ways to Build House of Cards",
  "Most Frequent Number Following Key In an Array",
  "Sort the Jumbled Numbers",
  "All Ancestors of a Node in a Directed Acyclic Graph",
  "Minimum Number of Moves to Make Palindrome",
  "Cells in a Range on an Excel Sheet",
  "Append K Integers With Minimal Sum",
  "Create Binary Tree From Descriptions",
  "Replace Non-Coprime Numbers in Array",
  "Number of Single Divisor Triplets",
  "Finding the Topic of Each Post",
  "Find All K-Distant Indices in an Array",
  "Count Artifacts That Can Be Extracted",
  "Maximize the Topmost Element After K Moves",
  "Minimum Weighted Subgraph With the Required Paths",
  "Distance to a Cycle in Undirected Graph",
  "The Number of Users That Are Eligible for Discount",
  "Divide Array Into Equal Pairs",
  "Maximize Number of Subsequences in a String",
  "Minimum Operations to Halve Array Sum",
  "Minimum White Tiles After Covering With Carpets",
  "Count Hills and Valleys in an Array",
  "Count Collisions on a Road",
  "Maximum Points in an Archery Competition",
  "Longest Substring of One Repeating Character",
  "Minimum Health to Beat Game",
  "Find the Difference of Two Arrays",
  "Minimum Deletions to Make Array Beautiful",
  "Find Palindrome With Fixed Length",
  "Maximum Value of K Coins From Piles",
  "Maximum Sum Score of Array",
  "Minimum Bit Flips to Convert Number",
  "Find Triangular Sum of an Array",
  "Number of Ways to Select Buildings",
  "Sum of Scores of Built Strings",
  "Minimum Number of Operations to Convert Time",
  "Find Players With Zero or One Losses",
  "Maximum Candies Allocated to K Children",
  "Encrypt and Decrypt Strings",
  "Users With Two Purchases Within Seven Days",
  "Check if an Array Is Consecutive",
  "The Users That Are Eligible for Discount",
  "Largest Number After Digit Swaps by Parity",
  "Minimize Result by Adding Parentheses to Expression",
  "Maximum Product After K Increments",
  "Maximum Total Beauty of the Gardens",
  "Add Two Integers",
  "Root Equals Sum of Children",
  "Count Positions on Street With Required Brightness",
  "Number of Times a Driver Was a Passenger",
  "Find Closest Number to Zero",
  "Number of Ways to Buy Pens and Pencils",
  "Design an ATM Machine",
  "Maximum Score of a Node Sequence",
  "Calculate Digit Sum of a String",
  "Minimum Rounds to Complete All Tasks",
  "Maximum Trailing Zeros in a Cornered Path",
  "Longest Path With Different Adjacent Characters",
  "Maximum Cost of Trip With K Highways",
  "Intersection of Multiple Arrays",
  "Count Lattice Points Inside a Circle",
  "Count Number of Rectangles Containing Each Point",
  "Number of Flowers in Full Bloom",
  "Dynamic Pivoting of a Table",
  "Dynamic Unpivoting of a Table",
  "Design Video Sharing Platform",
  "Count Prefixes of a Given String",
  "Minimum Average Difference",
  "Count Unguarded Cells in the Grid",
  "Escape the Spreading Fire",
  "Remove Digit From Number to Maximize Result",
  "Minimum Consecutive Cards to Pick Up",
  "K Divisible Elements Subarrays",
  "Total Appeal of A String",
  "Make Array Non-decreasing or Non-increasing",
  "Largest 3-Same-Digit Number in String",
  "Count Nodes Equal to Average of Subtree",
  "Count Number of Texts",
  "Check if There Is a Valid Parentheses String Path",
  "Minimum Number of Keypresses",
  "Find the K-Beauty of a Number",
  "Number of Ways to Split Array",
  "Maximum White Tiles Covered by a Carpet",
  "Substring With Largest Variance",
  "Find Resultant Array After Removing Anagrams",
  "Maximum Consecutive Floors Without Special Floors",
  "Largest Combination With Bitwise AND Greater Than Zero",
  "Count Integers in Intervals",
  "Closest Node to Path in Tree",
  "Percentage of Letter in String",
  "Maximum Bags With Full Capacity of Rocks",
  "Minimum Lines to Represent a Line Chart",
  "Sum of Total Strength of Wizards",
  "Number of People That Can Be Seen in a Grid",
  "Check if Number Has Equal Digit Count and Digit Value",
  "Sender With Largest Word Count",
  "Maximum Total Importance of Roads",
  "Booking Concert Tickets in Groups",
  "Rearrange Characters to Make Target String",
  "Apply Discount to Prices",
  "Steps to Make Array Non-decreasing",
  "Minimum Obstacle Removal to Reach Corner",
  "Maximum Profit From Trading Stocks",
  "Products With Three or More Orders in Two Consecutive Years",
  "Min Max Game",
  "Partition Array Such That Maximum Difference Is K",
  "Replace Elements in an Array",
  "Design a Text Editor",
  "Jump Game VIII",
  "Tasks Count in the Weekend",
  "Strong Password Checker II",
  "Successful Pairs of Spells and Potions",
  "Match Substring After Replacement",
  "Count Subarrays With Score Less Than K",
  "Calculate Amount Paid in Taxes",
  "Minimum Path Cost in a Grid",
  "Fair Distribution of Cookies",
  "Naming a Company",
  "Check for Contradictions in Equations",
  "Arrange Table by Gender",
  "Greatest English Letter in Upper and Lower Case",
  "Sum of Numbers With Units Digit K",
  "Longest Binary Subsequence Less Than or Equal to K",
  "Selling Pieces of Wood",
  "Minimum Flips in Binary Tree to Get Result",
  "The First Day of the Maximum Recorded Degree in Each City",
  "Count Asterisks",
  "Count Unreachable Pairs of Nodes in an Undirected Graph",
  "Maximum XOR After Operations",
  "Number of Distinct Roll Sequences",
  "Check if Matrix Is X-Matrix",
  "Count Number of Ways to Place Houses",
  "Maximum Score Of Spliced Array",
  "Minimum Score After Removals on a Tree",
  "Find Minimum Time to Finish All Jobs II",
  "Product Sales Analysis IV",
  "Decode the Message",
  "Spiral Matrix IV",
  "Number of People Aware of a Secret",
  "Number of Increasing Paths in a Grid",
  "Product Sales Analysis V",
  "Valid Palindrome IV",
  "Evaluate Boolean Binary Tree",
  "The Latest Time to Catch a Bus",
  "Minimum Sum of Squared Difference",
  "Subarray With Elements Greater Than Varying Threshold",
  "Minimum Amount of Time to Fill Cups",
  "Smallest Number in Infinite Set",
  "Move Pieces to Obtain a String",
  "Count the Number of Ideal Arrays",
  "All the Matches of the League",
  "Minimum Adjacent Swaps to Make a Valid Array",
  "Maximum Number of Pairs in Array",
  "Max Sum of a Pair With Equal Sum of Digits",
  "Query Kth Smallest Trimmed Number",
  "Minimum Deletions to Make Array Divisible",
  "Finding the Number of Visible Mountains",
  "Compute the Rank as a Percentage",
  "Best Poker Hand",
  "Number of Zero-Filled Subarrays",
  "Design a Number Container System",
  "Shortest Impossible Sequence of Rolls",
  "First Letter to Appear Twice",
  "Equal Row and Column Pairs",
  "Design a Food Rating System",
  "Number of Excellent Pairs",
  "Maximum Number of Books You Can Take",
  "Number of Unique Subjects Taught by Each Teacher",
  "Make Array Zero by Subtracting Equal Amounts",
  "Maximum Number of Groups Entering a Competition",
  "Find Closest Node to Given Two Nodes",
  "Longest Cycle in a Graph",
  "Minimum Costs Using the Train Line",
  "Generate the Invoice",
  "Merge Similar Items",
  "Count Number of Bad Pairs",
  "Task Scheduler II",
  "Minimum Replacements to Sort the Array",
  "Number of Arithmetic Triplets",
  "Reachable Nodes With Restrictions",
  "Check if There is a Valid Partition For The Array",
  "Longest Ideal Subsequence",
  "Minimize Maximum Value in a Grid",
  "Calculate the Influence of Each Salesperson",
  "Largest Local Values in a Matrix",
  "Node With Highest Edge Score",
  "Construct Smallest Number From DI String",
  "Count Special Integers",
  "Sort the Olympic Table",
  "Choose Edges to Maximize Score in a Tree",
  "Minimum Recolors to Get K Consecutive Black Blocks",
  "Time Needed to Rearrange a Binary String",
  "Shifting Letters II",
  "Maximum Segment Sum After Removals",
  "Minimum Hours of Training to Win a Competition",
  "Largest Palindromic Number",
  "Amount of Time for Binary Tree to Be Infected",
  "Find the K-Sum of an Array",
  "Median of a Row Wise Sorted Matrix",
  "Change Null Values in a Table to the Previous Value",
  "Longest Subsequence With Limited Sum",
  "Removing Stars From a String",
  "Minimum Amount of Time to Collect Garbage",
  "Build a Matrix With Conditions",
  "Count Strictly Increasing Subarrays",
  "Employees With Deductions",
  "Find Subarrays With Equal Sum",
  "Strictly Palindromic Number",
  "Maximum Rows Covered by Columns",
  "Maximum Number of Robots Within Budget",
  "Check Distances Between Same Letters",
  "Number of Ways to Reach a Position After Exactly k Steps",
  "Longest Nice Subarray",
  "Meeting Rooms III",
  "Minimum Time to Kill All Monsters",
  "Most Frequent Even Element",
  "Optimal Partition of String",
  "Divide Intervals Into Minimum Number of Groups",
  "Longest Increasing Subsequence II",
  "Design SQL",
  "Count Days Spent Together",
  "Maximum Matching of Players With Trainers",
  "Smallest Subarrays With Maximum Bitwise OR",
  "Minimum Money Required Before Transactions",
  "Smallest Even Multiple",
  "Length of the Longest Alphabetical Continuous Substring",
  "Reverse Odd Levels of Binary Tree",
  "Sum of Prefix Scores of Strings",
  "Closest Fair Integer",
  "Sort the People",
  "Longest Subarray With Maximum Bitwise AND",
  "Find All Good Indices",
  "Number of Good Paths",
  "Merge Operations to Turn Array Into a Palindrome",
  "Remove Letter To Equalize Frequency",
  "Longest Uploaded Prefix",
  "Bitwise XOR of All Pairings",
  "Number of Pairs Satisfying Inequality",
  "Number of Common Factors",
  "Maximum Sum of an Hourglass",
  "Minimize XOR",
  "Maximum Deletions on a String",
  "Maximize Total Tastiness of Purchased Fruits",
  "The Employee That Worked on the Longest Task",
  "Find The Original Array of Prefix Xor",
  "Using a Robot to Print the Lexicographically Smallest String",
  "Paths in Matrix Whose Sum Is Divisible by K",
  "Minimum Split Into Subarrays With GCD Greater Than One",
  "Number of Valid Clock Times",
  "Range Product Queries of Powers",
  "Minimize Maximum of Array",
  "Create Components With Same Value",
  "Largest Positive Integer That Exists With Its Negative",
  "Count Number of Distinct Integers After Reverse Operations",
  "Sum of Number and Its Reverse",
  "Count Subarrays With Fixed Bounds",
  "Number of Nodes With Value One",
  "Determine if Two Events Have Conflict",
  "Number of Subarrays With GCD Equal to K",
  "Minimum Cost to Make Array Equal",
  "Minimum Number of Operations to Make Arrays Similar",
  "Number of Distinct Binary Strings After Applying Operations",
  "Odd String Difference",
  "Words Within Two Edits of Dictionary",
  "Destroy Sequential Targets",
  "Next Greater Element IV",
  "Average Value of Even Numbers That Are Divisible by Three",
  "Most Popular Video Creator",
  "Minimum Addition to Make Integer Beautiful",
  "Height of Binary Tree After Subtree Removal Queries",
  "Sort Array by Moving Items to Empty Space",
  "Apply Operations to an Array",
  "Maximum Sum of Distinct Subarrays With Length K",
  "Total Cost to Hire K Workers",
  "Minimum Total Distance Traveled",
  "Minimum Subarrays in a Valid Split",
  "Number of Distinct Averages",
  "Count Ways To Build Good Strings",
  "Most Profitable Path in a Tree",
  "Split Message Based on Limit",
  "Convert the Temperature",
  "Number of Subarrays With LCM Equal to K",
  "Minimum Number of Operations to Sort a Binary Tree by Level",
  "Maximum Number of Non-overlapping Palindrome Substrings",
  "Minimum Cost to Buy Apples",
  "Customers With Strictly Increasing Purchases",
  "Number of Unequal Triplets in Array",
  "Closest Nodes Queries in a Binary Search Tree",
  "Minimum Fuel Cost to Report to the Capital",
  "Number of Beautiful Partitions",
  "Maximum XOR of Two Non-Overlapping Subtrees",
  "Form a Chemical Bond",
  "Minimum Cuts to Divide a Circle",
  "Difference Between Ones and Zeros in Row and Column",
  "Minimum Penalty for a Shop",
  "Count Palindromic Subsequences",
  "Find the Pivot Integer",
  "Append Characters to String to Make Subsequence",
  "Remove Nodes From Linked List",
  "Count Subarrays With Median K",
  "Number of Substrings With Fixed Ratio",
  "Circular Sentence",
  "Divide Players Into Teams of Equal Skill",
  "Minimum Score of a Path Between Two Cities",
  "Divide Nodes Into the Maximum Number of Groups",
  "Merge Overlapping Events in the Same Hall",
  "Number of Subarrays Having Even Product",
  "Maximum Value of a String in an Array",
  "Maximum Star Sum of a Graph",
  "Frog Jump II",
  "Minimum Total Cost to Make Arrays Unequal",
  "Delete Greatest Value in Each Row",
  "Longest Square Streak in an Array",
  "Design Memory Allocator",
  "Maximum Number of Points From Grid Queries",
  "Concatenate the Name and the Profession",
  "Bitwise OR of All Subsequence Sums",
  "Count Pairs Of Similar Strings",
  "Smallest Value After Replacing With Sum of Prime Factors",
  "Add Edges to Make Degrees of All Nodes Even",
  "Cycle Length Queries in a Tree",
  "Check if There is a Path With Equal Number of 0's And 1's",
  "Maximum Enemy Forts That Can Be Captured",
  "Reward Top K Students",
  "Minimize the Maximum of Two Arrays",
  "Count Anagrams",
  "Shortest Distance to Target String in a Circular Array",
  "Take K of Each Character From Left and Right",
  "Maximum Tastiness of Candy Basket",
  "Number of Great Partitions",
  "Count the Number of K-Big Indices",
  "Count the Digits That Divide a Number",
  "Distinct Prime Factors of Product of Array",
  "Partition String Into Substrings With Values at Most K",
  "Closest Prime Numbers in Range",
  "Maximum Frequency Score of a Subarray",
  "Categorize Box According to Criteria",
  "Find Consecutive Integers from a Data Stream",
  "Find Xor-Beauty of Array",
  "Maximize the Minimum Powered City",
  "Maximum Count of Positive Integer and Negative Integer",
  "Maximal Score After Applying K Operations",
  "Make Number of Distinct Characters Equal",
  "Time to Cross a Bridge",
  "Number of Good Binary Strings",
  "Time Taken to Cross the Door",
  "Difference Between Element Sum and Digit Sum of an Array",
  "Increment Submatrices by One",
  "Count the Number of Good Subarrays",
  "Difference Between Maximum and Minimum Price Sum",
  "Count the Number of Good Subsequences",
  "Minimum Common Value",
  "Minimum Operations to Make Array Equal II",
  "Maximum Subsequence Score",
  "Check if Point Is Reachable",
  "Alternating Digit Sum",
  "Sort the Students by Their Kth Score",
  "Apply Bitwise Operations to Make Strings Equal",
  "Minimum Cost to Split an Array",
  "Maximum Price to Fill a Bag",
  "Count Distinct Numbers on Board",
  "Count Collisions of Monkeys on a Polygon",
  "Put Marbles in Bags",
  "Count Increasing Quadruplets",
  "Separate the Digits in an Array",
  "Maximum Number of Integers to Choose From a Range I",
  "Maximize Win From Two Segments",
  "Disconnect Path in a Binary Matrix by at Most One Flip",
  "Maximum Number of Integers to Choose From a Range II",
  "Take Gifts From the Richest Pile",
  "Count Vowel Strings in Ranges",
  "House Robber IV",
  "Rearranging Fruits",
  "Find the Array Concatenation Value",
  "Count the Number of Fair Pairs",
  "Substring XOR Queries",
  "Subsequence With the Minimum Score",
  "Maximum Difference by Remapping a Digit",
  "Minimum Score by Changing Two Elements",
  "Minimum Impossible OR",
  "Handling Sum Queries After Update",
  "Merge Two 2D Arrays by Summing Values",
  "Minimum Operations to Reduce an Integer to 0",
  "Count the Number of Square-Free Subsets",
  "Find the String with LCP",
  "Left and Right Sum Differences",
  "Find the Divisibility Array of a String",
  "Find the Maximum Number of Marked Indices",
  "Minimum Time to Visit a Cell In a Grid",
  "Split With Minimum Sum",
  "Count Total Number of Colored Cells",
  "Count Ways to Group Overlapping Ranges",
  "Count Number of Possible Root Nodes",
  "Pass the Pillow",
  "Kth Largest Sum in a Binary Tree",
  "Split the Array to Make Coprime Products",
  "Number of Ways to Earn Points",
  "Count the Number of Vowel Strings in Range",
  "Rearrange Array to Maximize Prefix Score",
  "Count the Number of Beautiful Subarrays",
  "Minimum Time to Complete All Tasks",
  "Design a Todo List",
  "Distribute Money to Maximum Children",
  "Maximize Greatness of an Array",
  "Find Score of an Array After Marking All Elements",
  "Minimum Time to Repair Cars",
  "Number of Even and Odd Bits",
  "Check Knight Tour Configuration",
  "The Number of Beautiful Subsets",
  "Smallest Missing Non-negative Integer After Operations",
  "Make the Prefix Sum Non-negative",
  "K Items With the Maximum Sum",
  "Prime Subtraction Operation",
  "Minimum Operations to Make All Array Elements Equal",
  "Collect Coins in a Tree",
  "Minimum Time to Eat All Grains",
  "Form Smallest Number From Two Digit Arrays",
  "Find the Substring With Maximum Cost",
  "Make K-Subarray Sums Equal",
  "Shortest Cycle in a Graph",
  "Find the Longest Balanced Substring of a Binary String",
  "Convert an Array Into a 2D Array With Conditions",
  "Mice and Cheese",
  "Minimum Reverse Operations",
  "Beautiful Pairs",
  "Prime In Diagonal",
  "Sum of Distances",
  "Minimize the Maximum Difference of Pairs",
  "Minimum Number of Visited Cells in a Grid",
  "Check if Object Instance of Class",
  "Array Prototype Last",
  "Counter",
  "Sleep",
  "Cache With Time Limit",
  "Memoize",
  "Snail Traversal",
  "Flatten Deeply Nested Array",
  "Array Reduce Transformation",
  "Debounce",
  "JSON Deep Equal",
  "Function Composition",
  "Memoize II",
  "Group By",
  "Curry",
  "Convert Object to JSON String",
  "Filter Elements from Array",
  "Apply Transform Over Each Element in Array",
  "Promise Pool",
  "Promise Time Limit",
  "Count the Number of K-Free Subsets",
  "Find the Width of Columns of a Grid",
  "Find the Score of All Prefixes of an Array",
  "Cousins in Binary Tree II",
  "Design Graph With Shortest Path Calculator",
  "Row With Maximum Ones",
  "Find the Maximum Divisibility Score",
  "Minimum Additions to Make Valid String",
  "Minimize the Total Price of the Trips",
  "Color the Triangle Red",
  "Generate Fibonacci Sequence",
  "Nested Array Generator",
  "Design Cancellable Function",
  "Calculate Delayed Arrival Time",
  "Sum Multiples",
  "Sliding Subarray Beauty",
  "Minimum Number of Operations to Make All Array Elements Equal to 1",
  "Find Maximal Uncovered Ranges",
  "Maximum Sum With Exactly K Elements",
  "Find the Prefix Common Array of Two Arrays",
  "Maximum Number of Fish in a Grid",
  "Make Array Empty",
  "Determine the Winner of a Bowling Game",
  "First Completely Painted Row or Column",
  "Minimum Cost of a Path With Special Roads",
  "Lexicographically Smallest Beautiful String",
  "The Knight's Tour",
  "Counter II",
  "Allow One Function Call",
  "Create Hello World Function",
  "Find Latest Salaries",
  "Count Artist Occurrences On Spotify Ranking List",
  "Find the Distinct Difference Array",
  "Frequency Tracker",
  "Number of Adjacent Elements With the Same Color",
  "Make Costs of Paths Equal in a Binary Tree",
  "Split a Circular Linked List",
  "Array of Objects to Matrix",
  "Throttle",
  "Chunk Array",
  "Number of Senior Citizens",
  "Sum in a Matrix",
  "Maximum OR",
  "Power of Heroes",
  "Find the Losers of the Circular Game",
  "Neighboring Bitwise XOR",
  "Maximum Number of Moves in a Grid",
  "Count the Number of Complete Components",
  "Immediate Food Delivery III",
  "Bikes Last Time Used",
  "Find Active Users",
  "Extract Kth Character From The Rope Tree",
  "Infinite Method Object",
  "Immutability Helper",
  "Make Object Immutable",
  "Call Function with Custom Context",
  "Event Emitter",
  "Array Wrapper",
  "Minimum String Length After Removing Substrings",
  "Lexicographically Smallest Palindrome",
  "Find the Punishment Number of an Integer",
  "Modify Graph Edge Weights",
  "Differences Between Two Objects",
  "Consecutive Transactions with Increasing Amounts",
  "Minimum Operations to Make Numbers Non-positive",
  "Return Length of Arguments Passed",
  "To Be Or Not To Be",
  "Compact Object",
  "Buy Two Chocolates",
  "Extra Characters in a String",
  "Maximum Strength of a Group",
  "Greatest Common Divisor Traversal",
  "Remove Trailing Zeros From a String",
  "Difference of Number of Distinct Values on Diagonals",
  "Minimum Cost to Make All Characters Equal",
  "Maximum Strictly Increasing Cells in a Matrix",
  "Find Shortest Path with K Hops",
  "Execute Cancellable Function With Delay",
  "Minimize String Length",
  "Semi-Ordered Permutation",
  "Sum of Matrix After Queries",
  "Count of Integers",
  "Popularity Percentage",
  "Execute Asynchronous Functions in Parallel",
  "Join Two Arrays by ID",
  "Add Two Promises",
  "Sort By",
  "Interval Cancellation",
  "Calculator with Method Chaining",
  "Is Object Empty",
  "Count Houses in a Circular Street",
  "Check if The Number is Fascinating",
  "Find the Longest Semi-Repetitive Substring",
  "Movement of Robots",
  "Find a Good Subset of the Matrix",
  "Neither Minimum nor Maximum",
  "Lexicographically Smallest String After Substring Operation",
  "Collecting Chocolates",
  "Maximum Sum Queries",
  "Find the Closest Marked Node",
  "Count Occurrences in Text",
  "Total Distance Traveled",
  "Find the Value of the Partition",
  "Special Permutations",
  "Painting the Walls",
  "Count Substrings Without Repeating Character",
  "Find Maximum Number of String Pairs",
  "Construct the Longest New String",
  "Decremental String Concatenation",
  "Count Zero Request Servers",
  "Number of Beautiful Pairs",
  "Minimum Operations to Make the Integer Zero",
  "Ways to Split Array Into Good Subarrays",
  "Robot Collisions",
  "Customers with Maximum Number of Transactions on Consecutive Days",
  "Count Houses in a Circular Street II",
  "Bind Function to Context",
  "Deep Merge of Two Objects",
  "Query Batching",
  "Generate Circular Array Values",
  "Next Day",
  "Convert JSON String to Object",
];

export default leetcodeProblems